package com.paldexpro.ui.screens.mods

/**
 * Curated list from Steam Workshop collection "The Good Life"
 * https://steamcommunity.com/sharedfiles/filedetails/?id=3771025449
 *
 * Links open in an external browser / Steam app. Paldox does not install mods.
 */
data class WorkshopMod(
    val id: String,
    val nameEn: String,
    val nameRu: String,
    val author: String,
    val category: String,
    val descEn: String,
    val descRu: String,
    val workshopId: String,
    val required: Boolean = false,
) {
    val url: String get() = "https://steamcommunity.com/sharedfiles/filedetails/?id=$workshopId"
}

const val COLLECTION_URL =
    "https://steamcommunity.com/sharedfiles/filedetails/?id=3771025449"

val WorkshopMods: List<WorkshopMod> = listOf(
    WorkshopMod(
        id = "ue4ss",
        nameEn = "UE4SS Experimental (Palworld)",
        nameRu = "UE4SS Experimental (Palworld)",
        author = "Oak",
        category = "framework",
        descEn = "Core modding framework. Required by many QoL mods. Remove old UE4SS from Win64 before installing.",
        descRu = "Базовый фреймворк для модов. Нужен многим QoL-модам. Удалите старый UE4SS из Win64 перед установкой.",
        workshopId = "3625223587",
        required = true,
    ),
    WorkshopMod(
        id = "palschema",
        nameEn = "PalSchema",
        nameRu = "PalSchema",
        author = "Oak",
        category = "framework",
        descEn = "JSON-based data/blueprint patches with fewer conflicts. Often required together with UE4SS.",
        descRu = "Патчи data/blueprint через JSON с меньшим числом конфликтов. Часто нужен вместе с UE4SS.",
        workshopId = "3625280368",
        required = true,
    ),
    WorkshopMod(
        id = "expanded_world",
        nameEn = "Expanded World Options",
        nameRu = "Расширенные настройки мира",
        author = "ARAMA",
        category = "world",
        descEn = "Push world sliders beyond vanilla limits: day speed, combat, loot, grind and more.",
        descRu = "Слайдеры мира за пределы ванили: скорость дня, бой, лут, гринд и другое.",
        workshopId = "3697314514",
    ),
    WorkshopMod(
        id = "infinite_weight_camp",
        nameEn = "Infinite Weight In Camp",
        nameRu = "Бесконечный вес в лагере",
        author = "MeatKebab",
        category = "qol",
        descEn = "No weight limit while inside your base. Outside the camp, vanilla weight rules apply.",
        descRu = "Нет лимита веса на базе. За пределами лагеря — обычные правила веса.",
        workshopId = "3762076088",
    ),
    WorkshopMod(
        id = "pal_analyzer",
        nameEn = "Pal Analyzer",
        nameRu = "Анализатор палов",
        author = "Zac",
        category = "info",
        descEn = "Hover wild pals to see stats and details as you unlock more of the Paldex.",
        descRu = "Наведение на диких палов показывает статы и детали по мере открытия палдекса.",
        workshopId = "3677771546",
    ),
    WorkshopMod(
        id = "less_building",
        nameEn = "Less Building Restrictions",
        nameRu = "Меньше ограничений строительства",
        author = "KoZ",
        category = "building",
        descEn = "Build freer: sky builds, overlaps, angles that vanilla blocks.",
        descRu = "Свободнее стройка: в небе, с пересечениями, под углами, которые ваниль запрещает.",
        workshopId = "3625996709",
    ),
    WorkshopMod(
        id = "expanded_storage",
        nameEn = "Expanded Storage ×8",
        nameRu = "Расширенные склады ×8",
        author = "Chistix",
        category = "storage",
        descEn = "Palworld 1.0 compatible. Storage containers and expansion bags at 8× vanilla capacity.",
        descRu = "Совместимо с Palworld 1.0. Контейнеры и сумки расширения — 8× к ванили.",
        workshopId = "3766607347",
    ),
    WorkshopMod(
        id = "base_radius",
        nameEn = "Base Radius Improved",
        nameRu = "Улучшенный радиус базы",
        author = "nossr50",
        category = "base",
        descEn = "Base camp radius grows as the base levels up; the blue dome matches the real limit.",
        descRu = "Радиус базы растёт с уровнем; синий купол совпадает с реальным лимитом.",
        workshopId = "3765017449",
    ),
    WorkshopMod(
        id = "no_stuck_pals",
        nameEn = "No More Stuck Pals",
        nameRu = "Палы больше не застревают",
        author = "James",
        category = "qol",
        descEn = "Detects base pals stuck in pathing loops and teleports them free.",
        descRu = "Ловит застрявших палов на базе и телепортирует, чтобы они продолжили работу.",
        workshopId = "3764060163",
    ),
    WorkshopMod(
        id = "qol_pack",
        nameEn = "QualityOfLife",
        nameRu = "QualityOfLife",
        author = "yinqvanr3",
        category = "qol",
        descEn = "Multiplayer-friendly pack reducing grind and improving base management.",
        descRu = "Пак для мультиплеера: меньше гринда, удобнее управление базой.",
        workshopId = "3761921027",
    ),
    WorkshopMod(
        id = "faster_expedition",
        nameEn = "Faster Expedition Time 1.0",
        nameRu = "Быстрые экспедиции 1.0",
        author = "Shiroy",
        category = "qol",
        descEn = "Cuts expedition duration by ~75% without changing other systems.",
        descRu = "Сокращает время экспедиций примерно на 75%, остальное без изменений.",
        workshopId = "3766214649",
    ),
    WorkshopMod(
        id = "true_chest_loot",
        nameEn = "True Chest Loot (Schema)",
        nameRu = "Настоящий лут сундуков (Schema)",
        author = "Elendil",
        category = "loot",
        descEn = "Richer chest/boss loot: higher quantities and better rare drop odds.",
        descRu = "Более щедрый лут сундуков/боссов: больше предметов и лучше шансы на редкое.",
        workshopId = "3763990617",
    ),
    WorkshopMod(
        id = "smaller_plantations",
        nameEn = "Smaller Plantations",
        nameRu = "Маленькие грядки",
        author = "Syzzle",
        category = "building",
        descEn = "All plantations match berry plot size for denser, easier base layouts.",
        descRu = "Все плантации размера ягодных — плотнее и проще выравнивать базу.",
        workshopId = "3645372157",
    ),
    WorkshopMod(
        id = "fast_travel_anywhere",
        nameEn = "FastTravel Anywhere",
        nameRu = "Быстрое путешествие откуда угодно",
        author = "AuronNetwork",
        category = "travel",
        descEn = "Fast travel from the field to already unlocked destinations.",
        descRu = "Быстрое перемещение из поля к уже открытым точкам.",
        workshopId = "3767037030",
    ),
    WorkshopMod(
        id = "remote_palbox",
        nameEn = "Remote Palbox",
        nameRu = "Удалённый палбокс",
        author = "Atomic",
        category = "qol",
        descEn = "Open the Palbox anywhere (with vanilla-safe limits: not while riding / in dungeons).",
        descRu = "Открыть палбокс где угодно (с ванильными ограничениями: не верхом / не в данже).",
        workshopId = "3761594248",
    ),
    WorkshopMod(
        id = "smart_feeding",
        nameEn = "Smart Pal Feeding",
        nameRu = "Умное кормление палов",
        author = "Raysør",
        category = "base",
        descEn = "Pals eat smarter: configurable hunger threshold and satiety target at the food box.",
        descRu = "Палы едят умнее: порог голода и сытости у кормушки настраиваются.",
        workshopId = "3764497582",
    ),
    WorkshopMod(
        id = "minimap",
        nameEn = "YetAnotherMinimap",
        nameRu = "YetAnotherMinimap",
        author = "SvenBrnn",
        category = "ui",
        descEn = "In-game minimap with pals, boxes, eggs and more. Auto-hides in base by default.",
        descRu = "Миникарта в игре: палы, боксы, яйца. В базе обычно скрывается.",
        workshopId = "3630183149",
    ),
    WorkshopMod(
        id = "craft_x3",
        nameEn = "Balanced Crafting ×3",
        nameRu = "Сбалансированный крафт ×3",
        author = "梅川库梓",
        category = "craft",
        descEn = "Most recipes give 3× output with the same costs — less repetitive crafting.",
        descRu = "Большинство рецептов дают ×3 выход при той же цене — меньше рутинного крафта.",
        workshopId = "3764056655",
    ),
    WorkshopMod(
        id = "integrate_storage",
        nameEn = "Integrate all camp storage",
        nameRu = "Единое хранилище лагеря",
        author = "Luiter / Sarfflow",
        category = "storage",
        descEn = "Integrated camp storage access (ported from Nexus). Great for big bases.",
        descRu = "Объединённый доступ к складам базы (порт с Nexus). Удобно для больших баз.",
        workshopId = "3769924889",
    ),
)
