# -*- coding: utf-8 -*-
"""Enrich items/bosses in seed + download item icons from pindrop."""
import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "app/src/main/assets/seed_data.json"
ITEM_DIR = ROOT / "app/src/main/assets/items"

# Full item definitions for Paldox
ITEMS = [
    {
        "id": "pal_sphere", "nameEn": "Pal Sphere", "nameRu": "Пал-сфера",
        "category": "sphere", "rarity": "common",
        "descEn": "Basic sphere used to capture Pals. Works best on low-level and weakened targets.",
        "descRu": "Базовая сфера для ловли палов. Лучше работает на слабых и низкоуровневых целях.",
        "effectsEn": "Capture power: low", "effectsRu": "Сила захвата: низкая",
        "recipe": [{"itemId": "paldium_fragment", "qty": 1}, {"itemId": "wood", "qty": 3}, {"itemId": "stone", "qty": 3}],
        "craftStationEn": "Primitive Workbench", "craftStationRu": "Примитивный верстак",
        "techLevel": 2,
        "dropsEn": "Crafted; Vixy ranch can dig spheres", "dropsRu": "Крафт; Викси на ранчо может выкапывать сферы",
        "buyEn": "Some early merchants", "buyRu": "Некоторые ранние торговцы",
        "usesEn": "Capturing Pals", "usesRu": "Ловля палов",
        "icon": "items/pal_sphere.webp",
    },
    {
        "id": "mega_sphere", "nameEn": "Mega Sphere", "nameRu": "Мега-сфера",
        "category": "sphere", "rarity": "uncommon",
        "descEn": "Improved capture sphere with better success rate than Pal Sphere.",
        "descRu": "Улучшенная сфера с более высоким шансом захвата.",
        "effectsEn": "Capture power: medium", "effectsRu": "Сила захвата: средняя",
        "recipe": [{"itemId": "paldium_fragment", "qty": 2}, {"itemId": "ingot", "qty": 2}, {"itemId": "wood", "qty": 5}],
        "craftStationEn": "Sphere Workbench", "craftStationRu": "Верстак сфер",
        "techLevel": 14,
        "dropsEn": "Craft; chests; Vixy ranch", "dropsRu": "Крафт; сундуки; ранчо Викси",
        "buyEn": "Mid-game merchants", "buyRu": "Торговцы mid-game",
        "usesEn": "Capturing mid-level Pals", "usesRu": "Ловля палов среднего уровня",
        "icon": "items/mega_sphere.webp",
    },
    {
        "id": "giga_sphere", "nameEn": "Giga Sphere", "nameRu": "Гига-сфера",
        "category": "sphere", "rarity": "rare",
        "descEn": "High-grade sphere for stronger Pals.",
        "descRu": "Высококачественная сфера для сильных палов.",
        "effectsEn": "Capture power: high", "effectsRu": "Сила захвата: высокая",
        "recipe": [{"itemId": "paldium_fragment", "qty": 3}, {"itemId": "ingot", "qty": 5}, {"itemId": "quartz", "qty": 2}],
        "craftStationEn": "Sphere Workbench", "craftStationRu": "Верстак сфер",
        "techLevel": 20,
        "dropsEn": "Craft; higher chests", "dropsRu": "Крафт; лучшие сундуки",
        "buyEn": "Advanced merchants", "buyRu": "Продвинутые торговцы",
        "usesEn": "Capturing high-level Pals", "usesRu": "Ловля сильных палов",
        "icon": "items/giga_sphere.webp",
    },
    {
        "id": "hyper_sphere", "nameEn": "Hyper Sphere", "nameRu": "Гипер-сфера",
        "category": "sphere", "rarity": "rare",
        "descEn": "Advanced sphere with strong capture rate.",
        "descRu": "Продвинутая сфера с высокой силой захвата.",
        "effectsEn": "Capture power: very high", "effectsRu": "Сила захвата: очень высокая",
        "recipe": [{"itemId": "paldium_fragment", "qty": 5}, {"itemId": "pal_metal_ingot", "qty": 3}, {"itemId": "quartz", "qty": 5}],
        "craftStationEn": "Sphere Workbench", "craftStationRu": "Верстак сфер",
        "techLevel": 27,
        "dropsEn": "Craft; end-game chests", "dropsRu": "Крафт; поздние сундуки",
        "buyEn": "Rare merchants", "buyRu": "Редкие торговцы",
        "usesEn": "Capturing tough Pals", "usesRu": "Ловля сложных палов",
        "icon": "items/hyper_sphere.webp",
    },
    {
        "id": "ultra_sphere", "nameEn": "Ultra Sphere", "nameRu": "Ультра-сфера",
        "category": "sphere", "rarity": "epic",
        "descEn": "Very high capture power for late-game targets.",
        "descRu": "Очень высокая сила захвата для поздней игры.",
        "effectsEn": "Capture power: excellent", "effectsRu": "Сила захвата: отличная",
        "recipe": [{"itemId": "paldium_fragment", "qty": 8}, {"itemId": "pal_metal_ingot", "qty": 5}, {"itemId": "carbon_fiber", "qty": 3}],
        "craftStationEn": "Sphere Workbench", "craftStationRu": "Верстак сфер",
        "techLevel": 35,
        "dropsEn": "Craft; raids/chests", "dropsRu": "Крафт; рейды/сундуки",
        "buyEn": "Late merchants", "buyRu": "Поздние торговцы",
        "usesEn": "Capturing legendaries / bosses", "usesRu": "Ловля легендарок / боссов",
        "icon": "items/ultra_sphere.webp",
    },
    {
        "id": "legendary_sphere", "nameEn": "Legendary Sphere", "nameRu": "Легендарная сфера",
        "category": "sphere", "rarity": "legendary",
        "descEn": "Top-tier capture sphere for the hardest Pals.",
        "descRu": "Сфера высшего уровня для самых сложных палов.",
        "effectsEn": "Capture power: maximum", "effectsRu": "Сила захвата: максимальная",
        "recipe": [{"itemId": "paldium_fragment", "qty": 12}, {"itemId": "pal_metal_ingot", "qty": 10}, {"itemId": "ancient_civilization_parts", "qty": 2}],
        "craftStationEn": "Sphere Workbench", "craftStationRu": "Верстак сфер",
        "techLevel": 44,
        "dropsEn": "Craft; late chests", "dropsRu": "Крафт; поздние сундуки",
        "buyEn": "Very rare", "buyRu": "Очень редко",
        "usesEn": "Capturing end-game Pals", "usesRu": "Ловля эндгейм-палов",
        "icon": "items/legendary_sphere.webp",
    },
    {
        "id": "wood", "nameEn": "Wood", "nameRu": "Дерево",
        "category": "material", "rarity": "common",
        "descEn": "Basic building and crafting material obtained by chopping trees.",
        "descRu": "Базовый материал для стройки и крафта. Добывается рубкой деревьев.",
        "effectsEn": "Building / crafting material", "effectsRu": "Стройматериал / крафт",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Trees; lumbering Pals (Bushi, Wumpo…)", "dropsRu": "Деревья; палы с рубкой (Буши, Вумпо…)",
        "buyEn": "Usually not bought", "buyRu": "Обычно не покупается",
        "usesEn": "Structures, weapons, workbenches", "usesRu": "Постройки, оружие, верстаки",
        "icon": "items/wood.webp",
    },
    {
        "id": "stone", "nameEn": "Stone", "nameRu": "Камень",
        "category": "material", "rarity": "common",
        "descEn": "Common material from rocks and mining.",
        "descRu": "Обычный материал из камней и добычи.",
        "effectsEn": "Building / crafting", "effectsRu": "Стройка / крафт",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Rocks; mining Pals", "dropsRu": "Камни; добывающие палы",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Foundations, walls, furnaces", "usesRu": "Фундаменты, стены, печи",
        "icon": "items/stone.webp",
    },
    {
        "id": "fiber", "nameEn": "Fiber", "nameRu": "Волокно",
        "category": "material", "rarity": "common",
        "descEn": "Plant fiber gathered from bushes and small plants.",
        "descRu": "Растительное волокно из кустов и растений.",
        "effectsEn": "Crafting component", "effectsRu": "Компонент крафта",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Bushes; gathering", "dropsRu": "Кусты; сбор",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cloth, rope, early gear", "usesRu": "Ткань, верёвки, ранняя экипировка",
        "icon": "items/fiber.webp",
    },
    {
        "id": "ore", "nameEn": "Ore", "nameRu": "Руда",
        "category": "material", "rarity": "common",
        "descEn": "Raw metal ore mined from ore nodes.",
        "descRu": "Сырая металлическая руда из жил.",
        "effectsEn": "Smelts into Ingots", "effectsRu": "Плавится в слитки",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Ore nodes; Digtoise, Anubis, Astegon", "dropsRu": "Жилы; Дигтойз, Анубис, Астегон",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Smelted to Ingot", "usesRu": "Плавка в Слиток",
        "icon": "items/ore.webp",
    },
    {
        "id": "ingot", "nameEn": "Ingot", "nameRu": "Слиток",
        "category": "material", "rarity": "uncommon",
        "descEn": "Metal ingot smelted from Ore in a furnace.",
        "descRu": "Металлический слиток, выплавленный из руды в печи.",
        "effectsEn": "Mid-tier crafting metal", "effectsRu": "Металл mid-tier",
        "recipe": [{"itemId": "ore", "qty": 2}],
        "craftStationEn": "Furnace", "craftStationRu": "Печь",
        "techLevel": 10,
        "dropsEn": "Craft; chests", "dropsRu": "Крафт; сундуки",
        "buyEn": "Blacksmiths / merchants", "buyRu": "Кузнецы / торговцы",
        "usesEn": "Weapons, armor, spheres, structures", "usesRu": "Оружие, броня, сферы, постройки",
        "icon": "items/ingot.webp",
    },
    {
        "id": "coal", "nameEn": "Coal", "nameRu": "Уголь",
        "category": "material", "rarity": "common",
        "descEn": "Fuel and crafting material found in rocky areas.",
        "descRu": "Топливо и материал крафта в скалистых зонах.",
        "effectsEn": "Fuel / gunpowder chain", "effectsRu": "Топливо / цепочка пороха",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Coal nodes; mining", "dropsRu": "Угольные жилы; добыча",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Furnaces, ammo, advanced crafts", "usesRu": "Печи, патроны, продвинутый крафт",
        "icon": "items/coal.webp",
    },
    {
        "id": "quartz", "nameEn": "Pure Quartz", "nameRu": "Чистый кварц",
        "category": "material", "rarity": "uncommon",
        "descEn": "Crystal material mainly found in cold regions.",
        "descRu": "Кристаллический материал, в основном в холодных регионах.",
        "effectsEn": "Electronics / spheres", "effectsRu": "Электроника / сферы",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Snowy mountains quartz nodes", "dropsRu": "Кварц в снежных горах",
        "buyEn": "Rare", "buyRu": "Редко",
        "usesEn": "Circuit boards, advanced spheres", "usesRu": "Схемы, продвинутые сферы",
        "icon": "items/quartz.webp",
    },
    {
        "id": "crude_oil", "nameEn": "Crude Oil", "nameRu": "Сырая нефть",
        "category": "material", "rarity": "rare",
        "descEn": "Late-game resource from oil nodes / extractors.",
        "descRu": "Ресурс поздней игры с нефтяных точек / экстракторов.",
        "effectsEn": "Plastic / fuel chain", "effectsRu": "Пластик / топливо",
        "recipe": [], "craftStationEn": "Oil Extractor", "craftStationRu": "Нефтеэкстрактор",
        "techLevel": 36,
        "dropsEn": "Oil fields late-game", "dropsRu": "Нефтяные поля late-game",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Plastic, high-end production", "usesRu": "Пластик, высокоуровневое производство",
        "icon": "items/crude_oil.webp",
    },
    {
        "id": "pal_metal_ingot", "nameEn": "Pal Metal Ingot", "nameRu": "Пал-металл",
        "category": "material", "rarity": "rare",
        "descEn": "Advanced alloy for late-game gear and spheres.",
        "descRu": "Продвинутый сплав для late-game снаряжения и сфер.",
        "effectsEn": "High-tier metal", "effectsRu": "Металл высокого уровня",
        "recipe": [{"itemId": "ore", "qty": 3}, {"itemId": "paldium_fragment", "qty": 2}],
        "craftStationEn": "Improved Furnace", "craftStationRu": "Улучшенная печь",
        "techLevel": 34,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "Rare merchants", "buyRu": "Редкие торговцы",
        "usesEn": "Legendary gear, ultra spheres", "usesRu": "Легендарное снаряжение, ультра-сферы",
        "icon": "items/pal_metal_ingot.webp",
    },
    {
        "id": "paldium_fragment", "nameEn": "Paldium Fragment", "nameRu": "Фрагмент палдиума",
        "category": "material", "rarity": "common",
        "descEn": "Core resource used in spheres, tech, and many crafts.",
        "descRu": "Ключевой ресурс для сфер, технологий и крафта.",
        "effectsEn": "Universal craft resource", "effectsRu": "Универсальный ресурс крафта",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "World nodes; chests; bosses", "dropsRu": "Точки в мире; сундуки; боссы",
        "buyEn": "Merchants", "buyRu": "Торговцы",
        "usesEn": "Spheres, weapons, technology", "usesRu": "Сферы, оружие, технологии",
        "icon": "items/paldium_fragment.webp",
    },
    {
        "id": "carbon_fiber", "nameEn": "Carbon Fiber", "nameRu": "Углеволокно",
        "category": "material", "rarity": "rare",
        "descEn": "Lightweight strong material for advanced gear.",
        "descRu": "Лёгкий прочный материал для продвинутого снаряжения.",
        "effectsEn": "Late-game craft component", "effectsRu": "Компонент late-game",
        "recipe": [{"itemId": "coal", "qty": 2}, {"itemId": "fiber", "qty": 5}],
        "craftStationEn": "Production Assembly Line", "craftStationRu": "Сборочная линия",
        "techLevel": 42,
        "dropsEn": "Craft; chests", "dropsRu": "Крафт; сундуки",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Armor, weapons, spheres", "usesRu": "Броня, оружие, сферы",
        "icon": "items/carbon_fiber.webp",
    },
    {
        "id": "ancient_civilization_parts", "nameEn": "Ancient Civilization Parts", "nameRu": "Части древней цивилизации",
        "category": "material", "rarity": "epic",
        "descEn": "Rare parts dropped by tower bosses and powerful alphas.",
        "descRu": "Редкие части с башенных боссов и сильных альф.",
        "effectsEn": "Legendary crafts / spheres", "effectsRu": "Легендарный крафт / сферы",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Tower bosses; strong alphas", "dropsRu": "Башенные боссы; сильные альфы",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "High-end tech and legendary items", "usesRu": "Высокие технологии и легендарные предметы",
        "icon": "items/ancient_civilization_parts.webp",
    },
    {
        "id": "cake", "nameEn": "Cake", "nameRu": "Торт",
        "category": "food", "rarity": "uncommon",
        "descEn": "Required for breeding. Place in the Breeding Farm chest — does not spoil there.",
        "descRu": "Нужен для разведения. Кладите в сундук фермы — там не портится.",
        "effectsEn": "Enables breeding egg production", "effectsRu": "Включает производство яиц на ферме",
        "recipe": [
            {"itemId": "flour", "qty": 5}, {"itemId": "red_berries", "qty": 8},
            {"itemId": "milk", "qty": 7}, {"itemId": "egg", "qty": 8}, {"itemId": "honey", "qty": 2},
        ],
        "craftStationEn": "Cooking Pot / Electric Kitchen", "craftStationRu": "Котелок / Электрокухня",
        "techLevel": 17,
        "dropsEn": "Craft only (ingredients from ranch)", "dropsRu": "Только крафт (ингредиенты с ранчо)",
        "buyEn": "Sometimes merchants", "buyRu": "Иногда у торговцев",
        "usesEn": "Breeding Farm", "usesRu": "Ферма разведения",
        "icon": "items/cake.webp",
    },
    {
        "id": "red_berries", "nameEn": "Red Berries", "nameRu": "Красные ягоды",
        "category": "food", "rarity": "common",
        "descEn": "Basic early food. Can be cooked into Baked Berries.",
        "descRu": "Базовая ранняя еда. Можно запечь.",
        "effectsEn": "Restores hunger", "effectsRu": "Восстанавливает голод",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Berry bushes; Caprity ranch", "dropsRu": "Кусты ягод; ранчо Каприти",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Food; cake recipe", "usesRu": "Еда; рецепт торта",
        "icon": "items/red_berries.webp",
    },
    {
        "id": "baked_berries", "nameEn": "Baked Berries", "nameRu": "Печёные ягоды",
        "category": "food", "rarity": "common",
        "descEn": "Cooked berries with better food value.",
        "descRu": "Приготовленные ягоды с лучшей сытностью.",
        "effectsEn": "Better hunger restore", "effectsRu": "Лучше восстанавливает голод",
        "recipe": [{"itemId": "red_berries", "qty": 1}],
        "craftStationEn": "Campfire / Cooking Pot", "craftStationRu": "Костёр / Котелок",
        "techLevel": 1,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Player & Pal food", "usesRu": "Еда игрока и палов",
        "icon": "items/baked_berries.webp",
    },
    {
        "id": "egg", "nameEn": "Egg", "nameRu": "Яйцо",
        "category": "food", "rarity": "common",
        "descEn": "Farm product from Chikipi on the Ranch. Used in cooking and Cake.",
        "descRu": "Продукт ранчо с Чикипи. Нужен для готовки и Торта.",
        "effectsEn": "Cooking ingredient", "effectsRu": "Ингредиент готовки",
        "recipe": [], "craftStationEn": "Ranch (Chikipi)", "craftStationRu": "Ранчо (Чикипи)",
        "techLevel": 5,
        "dropsEn": "Chikipi ranch", "dropsRu": "Ранчо Чикипи",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cake, omelets, cooking", "usesRu": "Торт, омлеты, готовка",
        "icon": "items/egg.webp",
    },
    {
        "id": "milk", "nameEn": "Milk", "nameRu": "Молоко",
        "category": "food", "rarity": "common",
        "descEn": "Produced by Mozzarina on the Ranch.",
        "descRu": "Даёт Моццарина на Ранчо.",
        "effectsEn": "Cooking ingredient", "effectsRu": "Ингредиент готовки",
        "recipe": [], "craftStationEn": "Ranch (Mozzarina)", "craftStationRu": "Ранчо (Моццарина)",
        "techLevel": 5,
        "dropsEn": "Mozzarina ranch", "dropsRu": "Ранчо Моццарины",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cake and advanced food", "usesRu": "Торт и продвинутая еда",
        "icon": "items/milk.webp",
    },
    {
        "id": "honey", "nameEn": "Honey", "nameRu": "Мёд",
        "category": "food", "rarity": "uncommon",
        "descEn": "Produced by Beegarde on the Ranch. Key Cake ingredient.",
        "descRu": "Даёт Бигард на Ранчо. Ключевой ингредиент Торта.",
        "effectsEn": "Cooking / cake", "effectsRu": "Готовка / торт",
        "recipe": [], "craftStationEn": "Ranch (Beegarde)", "craftStationRu": "Ранчо (Бигард)",
        "techLevel": 5,
        "dropsEn": "Beegarde ranch", "dropsRu": "Ранчо Бигарда",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cake, sweets", "usesRu": "Торт, сладости",
        "icon": "items/honey.webp",
    },
    {
        "id": "flour", "nameEn": "Flour", "nameRu": "Мука",
        "category": "food", "rarity": "common",
        "descEn": "Milled wheat flour used for Cake and baking.",
        "descRu": "Мука из пшеницы для Торта и выпечки.",
        "effectsEn": "Baking ingredient", "effectsRu": "Ингредиент выпечки",
        "recipe": [{"itemId": "wheat", "qty": 1}],
        "craftStationEn": "Mill", "craftStationRu": "Мельница",
        "techLevel": 15,
        "dropsEn": "Craft from wheat farms", "dropsRu": "Крафт из пшеницы",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cake", "usesRu": "Торт",
        "icon": "items/flour.webp",
    },
    {
        "id": "wheat", "nameEn": "Wheat", "nameRu": "Пшеница",
        "category": "food", "rarity": "common",
        "descEn": "Crop grown at base plantations.",
        "descRu": "Культура с плантаций базы.",
        "effectsEn": "Mill into Flour", "effectsRu": "Перемалывается в муку",
        "recipe": [], "craftStationEn": "Plantation", "craftStationRu": "Плантация",
        "techLevel": 5,
        "dropsEn": "Farming Pals planting/gathering", "dropsRu": "Палы с посевом/сбором",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Flour → Cake", "usesRu": "Мука → Торт",
        "icon": "items/wheat.webp",
    },
    {
        "id": "wool", "nameEn": "Wool", "nameRu": "Шерсть",
        "category": "material", "rarity": "common",
        "descEn": "Soft material from Lamball and Cremis on Ranch.",
        "descRu": "Мягкий материал с Лэмбола и Кремиса на Ранчо.",
        "effectsEn": "Cloth crafting", "effectsRu": "Крафт ткани",
        "recipe": [], "craftStationEn": "Ranch", "craftStationRu": "Ранчо",
        "techLevel": 5,
        "dropsEn": "Lamball, Cremis ranch", "dropsRu": "Ранчо Лэмбол, Кремис",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cloth, armor, beds", "usesRu": "Ткань, броня, кровати",
        "icon": "items/wool.webp",
    },
    {
        "id": "high_quality_cloth", "nameEn": "High Quality Cloth", "nameRu": "Ткань HQ",
        "category": "material", "rarity": "uncommon",
        "descEn": "Refined cloth for better armor and furniture.",
        "descRu": "Качественная ткань для брони и мебели.",
        "effectsEn": "Armor craft component", "effectsRu": "Компонент брони",
        "recipe": [{"itemId": "wool", "qty": 2}],
        "craftStationEn": "Primitive Workbench", "craftStationRu": "Примитивный верстак",
        "techLevel": 10,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Armor, decorations", "usesRu": "Броня, декор",
        "icon": "items/high_quality_cloth.webp",
    },
    {
        "id": "assault_rifle", "nameEn": "Assault Rifle", "nameRu": "Штурмовая винтовка",
        "category": "weapon", "rarity": "rare",
        "descEn": "Reliable mid-to-late firearm for player DPS.",
        "descRu": "Надёжный огнестрел mid/late для урона игрока.",
        "effectsEn": "Ranged damage · uses rifle ammo", "effectsRu": "Дальний урон · винтовочные патроны",
        "recipe": [{"itemId": "refined_ingot", "qty": 30}, {"itemId": "polymer", "qty": 10}],
        "craftStationEn": "Weapon Workbench", "craftStationRu": "Оружейный верстак",
        "techLevel": 36,
        "dropsEn": "Craft; chests; bosses", "dropsRu": "Крафт; сундуки; боссы",
        "buyEn": "Black Marketeer (varies)", "buyRu": "Чёрный рынок (разное)",
        "usesEn": "Combat vs towers / bosses", "usesRu": "Бой против башен / боссов",
        "icon": "items/assault_rifle.webp",
    },
    {
        "id": "pump_action_shotgun", "nameEn": "Pump-Action Shotgun", "nameRu": "Помповый дробовик",
        "category": "weapon", "rarity": "rare",
        "descEn": "High close-range burst damage.",
        "descRu": "Высокий урон вблизи.",
        "effectsEn": "Close-range burst", "effectsRu": "Взрывной урон вблизи",
        "recipe": [{"itemId": "refined_ingot", "qty": 25}, {"itemId": "polymer", "qty": 8}],
        "craftStationEn": "Weapon Workbench", "craftStationRu": "Оружейный верстак",
        "techLevel": 30,
        "dropsEn": "Craft; chests", "dropsRu": "Крафт; сундуки",
        "buyEn": "Merchants", "buyRu": "Торговцы",
        "usesEn": "Boss openings, alpha fights", "usesRu": "Открытие боссов, альфы",
        "icon": "items/pump_action_shotgun.webp",
    },
    {
        "id": "rocket_launcher", "nameEn": "Rocket Launcher", "nameRu": "Ракетница",
        "category": "weapon", "rarity": "epic",
        "descEn": "Explosive heavy weapon. Great vs large bosses, watch friendly fire.",
        "descRu": "Взрывное тяжёлое оружие. Сильно против крупных боссов.",
        "effectsEn": "Explosive AOE damage", "effectsRu": "Взрывной AOE-урон",
        "recipe": [{"itemId": "pal_metal_ingot", "qty": 40}, {"itemId": "carbon_fiber", "qty": 15}],
        "craftStationEn": "Weapon Workbench", "craftStationRu": "Оружейный верстак",
        "techLevel": 45,
        "dropsEn": "Craft; late chests", "dropsRu": "Крафт; поздние сундуки",
        "buyEn": "Rare", "buyRu": "Редко",
        "usesEn": "Tower bosses, raids", "usesRu": "Башни, рейды",
        "icon": "items/rocket_launcher.webp",
    },
    {
        "id": "metal_helm", "nameEn": "Metal Helm", "nameRu": "Металлический шлем",
        "category": "armor", "rarity": "uncommon",
        "descEn": "Solid mid-game head armor.",
        "descRu": "Крепкий шлем середины игры.",
        "effectsEn": "Defense up", "effectsRu": "Повышает защиту",
        "recipe": [{"itemId": "ingot", "qty": 15}, {"itemId": "leather", "qty": 5}],
        "craftStationEn": "High Quality Workbench", "craftStationRu": "Качественный верстак",
        "techLevel": 18,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "Armor merchants", "buyRu": "Торговцы бронёй",
        "usesEn": "Player defense", "usesRu": "Защита игрока",
        "icon": "items/metal_helm.webp",
    },
    {
        "id": "heat_resistant_pelt_armor", "nameEn": "Heat Resistant Pelt Armor", "nameRu": "Жаростойкая броня",
        "category": "armor", "rarity": "uncommon",
        "descEn": "Protects against heat damage in deserts and volcanoes.",
        "descRu": "Защита от жары в пустынях и вулканах.",
        "effectsEn": "Heat resistance", "effectsRu": "Сопротивление жаре",
        "recipe": [{"itemId": "leather", "qty": 20}, {"itemId": "flame_organ", "qty": 10}],
        "craftStationEn": "High Quality Workbench", "craftStationRu": "Качественный верстак",
        "techLevel": 22,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Hot biomes exploration", "usesRu": "Исследование жарких биомов",
        "icon": "items/heat_resistant_pelt_armor.webp",
    },
    {
        "id": "cold_resistant_pelt_armor", "nameEn": "Cold Resistant Pelt Armor", "nameRu": "Морозостойкая броня",
        "category": "armor", "rarity": "uncommon",
        "descEn": "Protects against cold in snowy mountains.",
        "descRu": "Защита от холода в снежных горах.",
        "effectsEn": "Cold resistance", "effectsRu": "Сопротивление холоду",
        "recipe": [{"itemId": "leather", "qty": 20}, {"itemId": "ice_organ", "qty": 10}],
        "craftStationEn": "High Quality Workbench", "craftStationRu": "Качественный верстак",
        "techLevel": 22,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cold biomes / quartz farming", "usesRu": "Холодные биомы / фарм кварца",
        "icon": "items/cold_resistant_pelt_armor.webp",
    },
    {
        "id": "leather", "nameEn": "Leather", "nameRu": "Кожа",
        "category": "material", "rarity": "common",
        "descEn": "Dropped by many animal-like Pals. Used for armor.",
        "descRu": "Дроп с многих звероподобных палов. Нужна для брони.",
        "effectsEn": "Armor / furniture", "effectsRu": "Броня / мебель",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Rushoar, Direhowl, and many others", "dropsRu": "Рашор, Дайрхаул и многие другие",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Pelt armor, saddles", "usesRu": "Шкуряная броня, сёдла",
        "icon": "items/leather.webp",
    },
    {
        "id": "flame_organ", "nameEn": "Flame Organ", "nameRu": "Огненный орган",
        "category": "material", "rarity": "uncommon",
        "descEn": "Dropped by Fire Pals. Used in heat gear and crafts.",
        "descRu": "Дроп с огненных палов. Жаростойкая экипировка.",
        "effectsEn": "Fire craft component", "effectsRu": "Огненный компонент",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Foxparks, Arsox, Vanwyrm…", "dropsRu": "Фокспаркс, Арсокс, Ванвирм…",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Heat armor, ammo, tech", "usesRu": "Жаростойкая броня, патроны, тех.",
        "icon": "items/flame_organ.webp",
    },
    {
        "id": "ice_organ", "nameEn": "Ice Organ", "nameRu": "Ледяной орган",
        "category": "material", "rarity": "uncommon",
        "descEn": "Dropped by Ice Pals. Used in cold resistance crafts.",
        "descRu": "Дроп с ледяных палов. Крафт морозостойкости.",
        "effectsEn": "Ice craft component", "effectsRu": "Ледяной компонент",
        "recipe": [], "craftStationEn": "—", "craftStationRu": "—", "techLevel": 0,
        "dropsEn": "Pengullet, Foxcicle, Reindrix…", "dropsRu": "Пенгуллет, Фоксикл, Рейндрикс…",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Cold armor, tech", "usesRu": "Морозостойкая броня, тех.",
        "icon": "items/ice_organ.webp",
    },
    {
        "id": "refined_ingot", "nameEn": "Refined Ingot", "nameRu": "Очищенный слиток",
        "category": "material", "rarity": "rare",
        "descEn": "Higher quality metal for advanced weapons.",
        "descRu": "Металл высокого качества для продвинутого оружия.",
        "effectsEn": "Advanced metal", "effectsRu": "Продвинутый металл",
        "recipe": [{"itemId": "ore", "qty": 3}, {"itemId": "coal", "qty": 2}],
        "craftStationEn": "Improved Furnace", "craftStationRu": "Улучшенная печь",
        "techLevel": 28,
        "dropsEn": "Craft", "dropsRu": "Крафт",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Rifles, shotguns, armor", "usesRu": "Винтовки, дробовики, броня",
        "icon": "items/refined_ingot.webp",
    },
    {
        "id": "polymer", "nameEn": "Polymer", "nameRu": "Полимер",
        "category": "material", "rarity": "rare",
        "descEn": "Synthetic material refined from oil products.",
        "descRu": "Синтетический материал из нефтяной цепочки.",
        "effectsEn": "Late-game craft", "effectsRu": "Крафт late-game",
        "recipe": [{"itemId": "crude_oil", "qty": 2}],
        "craftStationEn": "Production Line", "craftStationRu": "Производственная линия",
        "techLevel": 40,
        "dropsEn": "Craft from oil", "dropsRu": "Крафт из нефти",
        "buyEn": "—", "buyRu": "—",
        "usesEn": "Firearms, high-tech gear", "usesRu": "Огнестрел, хай-тек",
        "icon": "items/polymer.webp",
    },
]

BOSSES = [
    {
        "order": 1, "id": "zoe_grizzbolt",
        "nameEn": "Zoe & Grizzbolt", "nameRu": "Зоя и Гризболт",
        "locationEn": "Rayne Syndicate Tower", "locationRu": "Башня Синдиката Рейн",
        "level": 10, "element1": "Electric", "element2": None,
        "imagePalId": "grizzbolt",
        "descEn": "The first tower boss. Zoe pilots Grizzbolt with heavy Electric attacks and minigun partner skills.",
        "descRu": "Первый башенный босс. Зоя управляет Гризболтом с сильными электрическими атаками и миниганом.",
        "strategyEn": "## Strategy\n1. Bring **Water** pals (Pengullet, Fuack, Penking)\n2. Stay mobile — Grizzbolt hits hard in melee\n3. Weaken with ranged weapons, then capture if wanted\n\n## Tips\n- Level ~11–15 recommended\n- Stock Mega Spheres\n- Use terrain to break line of sight",
        "strategyRu": "## Стратегия\n1. Берите **водных** палов (Пенгуллет, Фуак, Пенкинг)\n2. Держите дистанцию — Гризболт силён вблизи\n3. Ослабьте дальним боем, затем ловите при желании\n\n## Советы\n- Уровень ~11–15\n- Запас Мега-сфер\n- Используйте укрытия",
        "gearEn": "Early shotgun/bow · heat not required · stack Water pals",
        "gearRu": "Ранний дробовик/лук · жара не нужна · пачка водных палов",
        "counterPalIds": "penking,surfent,jormuntide,fuack,pengullet",
    },
    {
        "order": 2, "id": "lily_lyleen",
        "nameEn": "Lily & Lyleen", "nameRu": "Лили и Лайлин",
        "locationEn": "Free Pal Alliance Tower", "locationRu": "Башня Альянса Свободных Палов",
        "level": 25, "element1": "Grass", "element2": None,
        "imagePalId": "lyleen",
        "descEn": "Lily fights with Lyleen, a powerful Grass controller and healer-style threat with strong plant skills.",
        "descRu": "Лили сражается с Лайлин — сильный травяной контроллер с мощными растительными навыками.",
        "strategyEn": "## Strategy\n1. **Fire** pals excel (Arsox, Vanwyrm, Ragnahawk, Bushi)\n2. Interrupt planting / multi-target grass skills\n3. Bring fire resistance snacks if available\n\n## Tips\n- Mid-game armor and Giga Spheres\n- Flying fire mounts help reposition",
        "strategyRu": "## Стратегия\n1. **Огненные** палы сильны (Арсокс, Ванвирм, Рагнахок, Буши)\n2. Прерывайте массовые травяные скиллы\n3. Закуски с защитой от огня, если есть\n\n## Советы\n- Броня mid-game и Гига-сферы\n- Летающие огненные маунты для репозиционирования",
        "gearEn": "Heat-ready mid armor · Fire team · Giga Spheres",
        "gearRu": "Жаростойкая mid-броня · огненная команда · Гига-сферы",
        "counterPalIds": "ragnahawk,pyrin,blazehowl,vanwyrm,bushi",
    },
    {
        "order": 3, "id": "axel_orserk",
        "nameEn": "Axel & Orserk", "nameRu": "Аксель и Орсерк",
        "locationEn": "Brothers of the Eternal Pyre Tower", "locationRu": "Башня Братьев Вечного Пламени",
        "level": 35, "element1": "Electric", "element2": "Dragon",
        "imagePalId": "orserk",
        "descEn": "Axel rides Orserk — devastating Electric/Dragon DPS. High mobility and chain lightning style threats.",
        "descRu": "Аксель на Орсерке — разрушительный DPS Электричество/Дракон. Высокая мобильность и молнии.",
        "strategyEn": "## Strategy\n1. **Ground** pals help vs Electric (Anubis, Digtoise, Warsect)\n2. Watch Dragon coverage — Ice can help side-damage\n3. Keep healing items ready\n\n## Tips\n- Level 35+ recommended\n- Hyper Spheres if capturing\n- Don't stand in AoE beams",
        "strategyRu": "## Стратегия\n1. **Земляные** палы против электричества (Анубис, Дигтойз, Варсект)\n2. Учитывайте драконий урон — лёд как сайд\n3. Держите хил\n\n## Советы\n- Уровень 35+\n- Гипер-сферы для ловли\n- Не стойте в AoE-лучах",
        "gearEn": "Strong armor · Ground team · Hyper Spheres",
        "gearRu": "Крепкая броня · земляная команда · Гипер-сферы",
        "counterPalIds": "anubis,digtoise,warsect,gumoss,eikthyrdeer_terra",
    },
    {
        "order": 4, "id": "marcus_faleris",
        "nameEn": "Marcus & Faleris", "nameRu": "Маркус и Фалерис",
        "locationEn": "PIDF Tower", "locationRu": "Башня PIDF",
        "level": 45, "element1": "Fire", "element2": None,
        "imagePalId": "faleris",
        "descEn": "Marcus commands Faleris, a brutal Fire aerial threat with dive attacks and high burst.",
        "descRu": "Маркус с Фалерисом — жестокая огненная воздушная угроза с пикирующими атаками.",
        "strategyEn": "## Strategy\n1. **Water** and **Ground** recommended\n2. Jormuntide / Surfent / Anubis core\n3. Heat-resistant armor for the region\n\n## Tips\n- High mobility mounts\n- Ultra Spheres\n- Burst when Faleris lands",
        "strategyRu": "## Стратегия\n1. **Вода** и **Земля**\n2. Ядро: Йормунтид / Сёрфент / Анубис\n3. Жаростойкая броня региона\n\n## Советы\n- Мобильные маунты\n- Ультра-сферы\n- Берст, когда Фалерис садится",
        "gearEn": "Heat Resistant Armor · Water/Ground team · Ultra Spheres",
        "gearRu": "Жаростойкая броня · вода/земля · Ультра-сферы",
        "counterPalIds": "jormuntide,surfent,anubis,penking,azurobe",
    },
    {
        "order": 5, "id": "victor_shadowbeak",
        "nameEn": "Victor & Shadowbeak", "nameRu": "Виктор и Шэдоубик",
        "locationEn": "PAL Genetic Research Unit Tower", "locationRu": "Башня Генетических исследований PAL",
        "level": 50, "element1": "Dark", "element2": None,
        "imagePalId": "shadowbeak",
        "descEn": "Final classic tower. Victor's Shadowbeak is a Dark aerial nuke platform with brutal skills.",
        "descRu": "Финальная классическая башня. Шэдоубик Виктора — тёмная воздушная платформа с жестокими скиллами.",
        "strategyEn": "## Strategy\n1. **Dragon** and **Neutral** strong options\n2. Jetragon, Paladius, Astegon recommended\n3. Perfect passives + high level team\n\n## Tips\n- Legendary gear\n- Legendary/Ultra Spheres\n- Learn telegraphs — one combo can wipe",
        "strategyRu": "## Стратегия\n1. **Дракон** и **Нейтрал**\n2. Джетрагон, Паладиус, Астегон\n3. Идеальные пассивки + высокий уровень\n\n## Советы\n- Легендарное снаряжение\n- Легендарные/Ультра сферы\n- Учите телеграфы — одна комба может убить",
        "gearEn": "End-game armor/weapons · Dragon/Neutral · Legendary Spheres",
        "gearRu": "Эндгейм броня/оружие · дракон/нейтрал · Легендарные сферы",
        "counterPalIds": "jetragon,paladius,astegon,orserk,necromus",
    },
]


def fix_bosses(raw):
    fixed = []
    for b in raw:
        b = {k.strip(): v for k, v in b.items()}
        fixed.append(b)
    return fixed


def download_item_icons(ids):
    ITEM_DIR.mkdir(parents=True, exist_ok=True)
    ok, fail = 0, []
    for iid in ids:
        slug = iid.replace("_", "-")
        dest = ITEM_DIR / f"{iid}.webp"
        if dest.exists() and dest.stat().st_size > 400:
            ok += 1
            continue
        url = f"https://pindrop.gg/items/{slug}.webp"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 Paldox/1.1"})
            with urllib.request.urlopen(req, timeout=15) as r:
                data = r.read()
            if len(data) < 200 or b"<html" in data[:80].lower():
                fail.append(iid)
                continue
            dest.write_bytes(data)
            ok += 1
            print("item OK", iid, len(data))
        except Exception as e:
            fail.append(f"{iid}:{e}")
            print("item FAIL", iid, e)
    print(f"Items icons: {ok} ok, {len(fail)} fail")


def main():
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    seed["items"] = ITEMS
    seed["bosses"] = fix_bosses(BOSSES)
    seed["version"] = max(int(seed.get("version", 1)), 3)
    SEED.write_text(json.dumps(seed, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print("Seed items", len(ITEMS), "bosses", len(seed["bosses"]))
    download_item_icons([i["id"] for i in ITEMS])


if __name__ == "__main__":
    main()
