# -*- coding: utf-8 -*-
"""Generate PalDex Pro seed_data.json and project directories."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

pals_raw = [
("lamball","001","Lamball","Лэмбол","Neutral",None,1470,True,252,"common"),
("cattiva","002","Cattiva","Кэттива","Neutral",None,1460,True,271,"common"),
("chikipi","003","Chikipi","Чикипи","Neutral",None,1500,True,288,"common"),
("lifmunk","004","Lifmunk","Лифманк","Grass",None,1430,True,231,"common"),
("foxparks","005","Foxparks","Фокспаркс","Fire",None,1400,True,245,"common"),
("foxparks_cryst","005B","Foxparks Cryst","Фокспаркс Кристалл","Ice",None,1305,False,462,"uncommon"),
("fuack","006","Fuack","Фуак","Water",None,1330,True,284,"common"),
("sparkit","007","Sparkit","Спаркит","Electric",None,1410,True,291,"common"),
("tanzee","008","Tanzee","Танзи","Grass",None,1250,True,335,"common"),
("rooby","009","Rooby","Руби","Fire",None,1155,True,374,"common"),
("pengullet","010","Pengullet","Пенгуллет","Water",None,1350,True,248,"common"),
("penking","011","Penking","Пенкинг","Water","Ice",520,True,353,"rare"),
("jolthog","012","Jolthog","Джолтхог","Electric",None,1370,True,242,"common"),
("jolthog_cryst","012B","Jolthog Cryst","Джолтхог Кристалл","Ice",None,1360,False,243,"uncommon"),
("gumoss","013","Gumoss","Гумосс","Grass","Ground",1240,True,340,"common"),
("vixy","014","Vixy","Викси","Neutral",None,1450,True,306,"common"),
("hoocrates","015","Hoocrates","Хоукратес","Dark",None,1390,True,610,"common"),
("teafant","016","Teafant","Тифант","Water",None,1490,True,238,"common"),
("depresso","017","Depresso","Депрессо","Dark",None,1380,True,272,"common"),
("cremis","018","Cremis","Кремис","Neutral",None,1455,True,371,"common"),
("daedream","019","Daedream","Дейдрим","Dark",None,1230,True,334,"common"),
("rushoar","020","Rushoar","Рашор","Ground",None,1130,True,230,"common"),
("nox","021","Nox","Нокс","Dark",None,1180,True,352,"uncommon"),
("fuddler","022","Fuddler","Фаддлер","Ground",None,1220,True,329,"common"),
("killamari","023","Killamari","Килламари","Dark",None,1290,True,313,"common"),
("mau","024","Mau","Мау","Dark",None,1480,True,228,"common"),
("mau_cryst","024B","Mau Cryst","Мау Кристалл","Ice",None,1440,False,229,"uncommon"),
("celaray","025","Celaray","Селарей","Water",None,870,True,363,"uncommon"),
("direhowl","026","Direhowl","Дайрхаул","Neutral",None,1060,True,239,"uncommon"),
("tocotoco","027","Tocotoco","Токотоко","Neutral",None,1340,True,232,"common"),
("flopie","028","Flopie","Флопи","Grass",None,1280,True,319,"common"),
("mozzarina","029","Mozzarina","Моццарина","Neutral",None,910,True,314,"uncommon"),
("bristla","030","Bristla","Бристла","Grass",None,1320,True,246,"common"),
("gobfin","031","Gobfin","Гобфин","Water",None,1090,True,250,"uncommon"),
("gobfin_ignis","031B","Gobfin Ignis","Гобфин Игнис","Fire",None,1100,False,251,"uncommon"),
("hangyu","032","Hangyu","Хангью","Ground",None,1420,True,256,"common"),
("hangyu_cryst","032B","Hangyu Cryst","Хангью Кристалл","Ice",None,1422,False,257,"uncommon"),
("mossanda","033","Mossanda","Моссанда","Grass",None,430,True,325,"rare"),
("mossanda_lux","033B","Mossanda Lux","Моссанда Люкс","Electric",None,390,False,326,"epic"),
("woolipop","034","Woolipop","Вулипоп","Neutral",None,1190,True,264,"common"),
("caprity","035","Caprity","Каприти","Grass",None,930,True,302,"uncommon"),
("caprity_noct","035B","Caprity Noct","Каприти Нокт","Dark",None,855,False,463,"uncommon"),
("melpaca","036","Melpaca","Мелпака","Neutral",None,890,True,266,"uncommon"),
("eikthyrdeer","037","Eikthyrdeer","Эйктирдир","Neutral",None,920,True,233,"uncommon"),
("eikthyrdeer_terra","037B","Eikthyrdeer Terra","Эйктирдир Терра","Ground",None,900,False,234,"uncommon"),
("nitewing","038","Nitewing","Найтвинг","Neutral",None,420,True,318,"rare"),
("ribbuny","039","Ribbuny","Риббани","Neutral",None,1310,True,347,"common"),
("ribbuny_botan","039B","Ribbuny Botan","Риббани Ботан","Grass",None,1205,False,464,"uncommon"),
("incineram","040","Incineram","Инсинерам","Fire","Dark",590,True,226,"rare"),
("incineram_noct","040B","Incineram Noct","Инсинерам Нокт","Dark",None,580,False,227,"rare"),
("cinnamoth","041","Cinnamoth","Синнамот","Grass",None,490,True,367,"rare"),
("arsox","042","Arsox","Арсокс","Fire",None,790,True,327,"uncommon"),
("dumud","043","Dumud","Думуд","Ground",None,895,True,372,"uncommon"),
("cawgnito","044","Cawgnito","Когнито","Dark",None,1080,True,269,"uncommon"),
("leezpunk","045","Leezpunk","Лизпанк","Dark",None,1120,True,282,"uncommon"),
("leezpunk_ignis","045B","Leezpunk Ignis","Лизпанк Игнис","Fire",None,1140,False,283,"uncommon"),
("loupmoon","046","Loupmoon","Лупмун","Dark",None,950,True,255,"uncommon"),
("loupmoon_cryst","046B","Loupmoon Cryst","Лупмун Кристалл","Ice",None,805,False,465,"uncommon"),
("galeclaw","047","Galeclaw","Гейлкло","Neutral",None,1030,True,236,"uncommon"),
("robinquill","048","Robinquill","Робинквилл","Grass",None,1020,True,277,"uncommon"),
("robinquill_terra","048B","Robinquill Terra","Робинквилл Терра","Grass","Ground",1000,False,278,"uncommon"),
("gorirat","049","Gorirat","Горират","Neutral",None,1040,True,240,"uncommon"),
("gorirat_terra","049B","Gorirat Terra","Горират Терра","Ground",None,1030,False,241,"uncommon"),
("beegarde","050","Beegarde","Бигард","Grass",None,1070,True,323,"uncommon"),
("elizabee","051","Elizabee","Элизаби","Grass",None,330,True,322,"epic"),
("grintale","052","Grintale","Гринтэйл","Neutral",None,510,True,366,"rare"),
("swee","053","Swee","Сви","Ice",None,1300,True,343,"common"),
("sweepa","054","Sweepa","Свипа","Ice",None,410,True,344,"rare"),
("chillet","055","Chillet","Чиллет","Ice","Dragon",800,True,354,"uncommon"),
("chillet_ignis","055B","Chillet Ignis","Чиллет Игнис","Fire","Dragon",790,False,355,"uncommon"),
("univolt","056","Univolt","Юнивольт","Electric",None,680,True,244,"rare"),
("foxcicle","057","Foxcicle","Фоксикл","Ice",None,760,True,332,"uncommon"),
("pyrin","058","Pyrin","Пайрин","Fire",None,360,True,260,"epic"),
("pyrin_noct","058B","Pyrin Noct","Пайрин Нокт","Fire","Dark",240,False,261,"epic"),
("reindrix","059","Reindrix","Рейндрикс","Ice",None,880,True,303,"uncommon"),
("rayhound","060","Rayhound","Рейхаунд","Electric",None,740,True,328,"uncommon"),
("kitsun","061","Kitsun","Китсун","Fire",None,830,True,281,"uncommon"),
("kitsun_noct","061B","Kitsun Noct","Китсун Нокт","Dark",None,735,False,466,"rare"),
("dazzi","062","Dazzi","Дэззи","Electric",None,1210,True,249,"common"),
("dazzi_noct","062B","Dazzi Noct","Дэззи Нокт","Dark",None,1115,False,467,"uncommon"),
("lunaris","063","Lunaris","Лунарис","Neutral",None,1110,True,247,"uncommon"),
("dinossom","064","Dinossom","Диноссом","Grass","Dragon",820,True,289,"uncommon"),
("dinossom_lux","064B","Dinossom Lux","Диноссом Люкс","Electric","Dragon",810,False,290,"uncommon"),
("surfent","065","Surfent","Сёрфент","Water",None,560,True,267,"rare"),
("surfent_terra","065B","Surfent Terra","Сёрфент Терра","Ground",None,550,False,288,"rare"),
("maraith","066","Maraith","Марайт","Dark",None,1150,True,276,"uncommon"),
("digtoise","067","Digtoise","Дигтойз","Ground",None,850,True,235,"uncommon"),
("tombat","068","Tombat","Томбат","Dark",None,750,True,324,"uncommon"),
("lovander","069","Lovander","Ловандер","Neutral",None,940,True,309,"uncommon"),
("flambelle","070","Flambelle","Фламбель","Fire",None,1405,True,373,"common"),
("vanwyrm","071","Vanwyrm","Ванвирм","Fire","Dark",660,True,286,"rare"),
("vanwyrm_cryst","071B","Vanwyrm Cryst","Ванвирм Кристалл","Ice","Dark",620,False,287,"rare"),
("bushi","072","Bushi","Буши","Fire",None,640,True,361,"rare"),
("bushi_noct","072B","Bushi Noct","Буши Нокт","Fire","Dark",650,False,362,"rare"),
("beakon","073","Beakon","Бикон","Electric",None,220,True,348,"epic"),
("ragnahawk","074","Ragnahawk","Рагнахок","Fire",None,380,True,360,"epic"),
("katress","075","Katress","Катресс","Dark",None,700,True,345,"rare"),
("katress_ignis","075B","Katress Ignis","Катресс Игнис","Fire","Dark",690,False,346,"rare"),
("wixen","076","Wixen","Виксен","Fire",None,1160,True,307,"uncommon"),
("wixen_noct","076B","Wixen Noct","Виксен Нокт","Fire","Dark",1150,False,308,"uncommon"),
("verdash","077","Verdash","Вердаш","Grass",None,990,True,331,"uncommon"),
("vaelet","078","Vaelet","Вэйлет","Grass",None,1050,True,317,"uncommon"),
("sibelyx","079","Sibelyx","Сибеликс","Ice",None,450,True,305,"rare"),
("elphidran","080","Elphidran","Эльфидран","Dragon",None,540,True,262,"rare"),
("elphidran_aqua","080B","Elphidran Aqua","Эльфидран Аква","Dragon","Water",530,False,263,"rare"),
("kelpsea","081","Kelpsea","Келпси","Water",None,1260,True,311,"common"),
("kelpsea_ignis","081B","Kelpsea Ignis","Келпси Игнис","Fire",None,1270,True,312,"common"),
("azurobe","082","Azurobe","Азуробе","Water","Dragon",500,True,270,"rare"),
("cryolinx","083","Cryolinx","Крайолинкс","Ice",None,130,True,265,"epic"),
("cryolinx_terra","083B","Cryolinx Terra","Крайолинкс Терра","Ground",None,160,True,468,"epic"),
("blazehowl","084","Blazehowl","Блейзхаул","Fire",None,710,True,336,"rare"),
("blazehowl_noct","084B","Blazehowl Noct","Блейзхаул Нокт","Fire","Dark",670,False,337,"rare"),
("relaxaurus","085","Relaxaurus","Релаксозавр","Dragon","Water",280,True,279,"epic"),
("relaxaurus_lux","085B","Relaxaurus Lux","Релаксозавр Люкс","Dragon","Electric",270,False,280,"epic"),
("broncherry","086","Broncherry","Брончерри","Grass",None,860,True,297,"uncommon"),
("broncherry_aqua","086B","Broncherry Aqua","Брончерри Аква","Grass","Water",840,False,298,"uncommon"),
("petallia","087","Petallia","Петаллия","Grass",None,780,True,365,"uncommon"),
("reptyro","088","Reptyro","Рептиро","Fire","Ground",320,True,274,"epic"),
("reptyro_cryst","088B","Reptyro Cryst","Рептиро Кристалл","Ice","Ground",230,False,275,"epic"),
("kingpaca","089","Kingpaca","Кингпака","Neutral",None,470,True,338,"rare"),
("kingpaca_cryst","089B","Kingpaca Cryst","Кингпака Кристалл","Ice",None,440,False,339,"rare"),
("mammorest","090","Mammorest","Мамморест","Grass",None,300,True,294,"epic"),
("mammorest_cryst","090B","Mammorest Cryst","Мамморест Кристалл","Ice",None,290,False,295,"epic"),
("wumpo","091","Wumpo","Вумпо","Ice",None,460,True,315,"rare"),
("wumpo_botan","091B","Wumpo Botan","Вумпо Ботан","Grass",None,480,True,316,"rare"),
("warsect","092","Warsect","Варсект","Ground","Grass",340,True,349,"epic"),
("warsect_terra","092B","Warsect Terra","Варсект Терра","Ground",None,350,False,350,"epic"),
("fenglope","093","Fenglope","Фенглоп","Neutral",None,980,True,273,"uncommon"),
("fenglope_lux","093B","Fenglope Lux","Фенглоп Люкс","Electric",None,835,False,469,"uncommon"),
("felbat","094","Felbat","Фелбат","Dark",None,1010,True,296,"uncommon"),
("quivern","095","Quivern","Квиверн","Dragon",None,350,True,356,"epic"),
("quivern_botan","095B","Quivern Botan","Квиверн Ботан","Dragon","Grass",340,True,357,"epic"),
("blazamut","096","Blazamut","Блазамут","Fire",None,10,True,300,"legendary"),
("blazamut_ryu","096B","Blazamut Ryu","Блазамут Рю","Dragon","Fire",9,False,301,"legendary"),
("helzephyr","097","Helzephyr","Хелзефир","Dark",None,190,True,358,"epic"),
("helzephyr_lux","097B","Helzephyr Lux","Хелзефир Люкс","Dark","Electric",180,False,359,"epic"),
("astegon","098","Astegon","Астегон","Dragon","Dark",150,True,330,"epic"),
("menasting","099","Menasting","Менастинг","Dark","Ground",260,True,368,"epic"),
("menasting_terra","099B","Menasting Terra","Менастинг Терра","Ground",None,250,False,369,"epic"),
("anubis","100","Anubis","Анубис","Ground",None,570,True,225,"rare"),
("jormuntide","101","Jormuntide","Йормунтид","Dragon","Water",310,True,253,"epic"),
("jormuntide_ignis","101B","Jormuntide Ignis","Йормунтид Игнис","Dragon","Fire",315,False,254,"epic"),
("suzaku","102","Suzaku","Судзаку","Fire",None,50,True,258,"legendary"),
("suzaku_aqua","102B","Suzaku Aqua","Судзаку Аква","Water",None,30,False,259,"legendary"),
("grizzbolt","103","Grizzbolt","Гризболт","Electric",None,200,False,237,"epic"),
("lyleen","104","Lyleen","Лайлин","Grass",None,250,False,320,"epic"),
("lyleen_noct","104B","Lyleen Noct","Лайлин Нокт","Dark",None,210,False,321,"epic"),
("faleris","105","Faleris","Фалерис","Fire",None,370,False,299,"epic"),
("faleris_aqua","105B","Faleris Aqua","Фалерис Аква","Water",None,245,False,470,"epic"),
("orserk","106","Orserk","Орсерк","Dragon","Electric",140,False,370,"legendary"),
("shadowbeak","107","Shadowbeak","Шэдоубик","Dark",None,60,False,304,"legendary"),
("paladius","108","Paladius","Паладиус","Neutral",None,80,False,351,"legendary"),
("necromus","109","Necromus","Некромус","Dark",None,70,False,364,"legendary"),
("frostallion","110","Frostallion","Фросталлион","Ice",None,120,False,292,"legendary"),
("frostallion_noct","110B","Frostallion Noct","Фросталлион Нокт","Dark",None,100,False,293,"legendary"),
("jetragon","111","Jetragon","Джетрагон","Dragon",None,90,False,333,"legendary"),
("bellanoir","112","Bellanoir","Беллануар","Dark",None,1,False,375,"legendary"),
("bellanoir_libero","112B","Bellanoir Libero","Беллануар Либеро","Dark",None,1,False,376,"legendary"),
("selyne","113","Selyne","Селин","Dark","Neutral",345,False,377,"epic"),
("croajiro","114","Croajiro","Кроахиро","Water",None,795,True,378,"uncommon"),
("lullu","115","Lullu","Луллу","Grass",None,905,True,379,"uncommon"),
("shroomer","116","Shroomer","Шрумер","Grass",None,720,True,380,"rare"),
("shroomer_noct","116B","Shroomer Noct","Шрумер Нокт","Grass","Dark",730,True,381,"rare"),
("kikit","117","Kikit","Кикит","Ground",None,1125,False,382,"uncommon"),
("sootseer","118","Sootseer","Сутсир","Dark","Fire",545,False,383,"rare"),
("prixter","119","Prixter","Прикстер","Dark","Ground",355,False,384,"epic"),
("knocklem","120","Knocklem","Ноклем","Ground",None,265,False,385,"epic"),
("yakumo","121","Yakumo","Якумо","Neutral",None,945,False,386,"uncommon"),
("dogen","122","Dogen","Доген","Neutral",None,665,False,387,"rare"),
("dazemu","123","Dazemu","Дазему","Ground",None,675,False,388,"rare"),
("mimog","124","Mimog","Мимог","Neutral",None,1200,False,389,"uncommon"),
("xenovader","125","Xenovader","Ксеновадер","Dark",None,465,False,390,"rare"),
("xenogard","126","Xenogard","Ксеногард","Dragon",None,435,False,391,"rare"),
("xenolord","127","Xenolord","Ксенолорд","Dark","Dragon",265,False,393,"epic"),
("nitemary","128","Nitemary","Найтмери","Dark",None,705,True,394,"rare"),
("starryon","129","Starryon","Старрион","Dark",None,365,True,395,"epic"),
("silvegis","130","Silvegis","Сильвегис","Dragon",None,215,True,396,"epic"),
("smokie","131","Smokie","Смоки","Dark",None,1245,True,397,"common"),
("celesdir","132","Celesdir","Селесдир","Neutral",None,815,False,398,"uncommon"),
("omascul","133","Omascul","Омаскул","Dark",None,630,True,400,"rare"),
("splatterina","134","Splatterina","Сплаттерина","Dark",None,725,True,404,"rare"),
("tarantriss","135","Tarantriss","Тарантрисс","Dark",None,825,True,405,"uncommon"),
("azurmane","136","Azurmane","Азурмейн","Electric",None,400,True,406,"rare"),
("bastigor","137","Bastigor","Бастигор","Ice",None,170,False,472,"epic"),
("prunelia","138","Prunelia","Прунелия","Grass",None,755,True,20,"uncommon"),
("nyafia","139","Nyafia","Ньяфия","Dark",None,645,True,19,"rare"),
("gildane","140","Gildane","Гилдейн","Ground",None,505,True,219,"rare"),
]

partner_skills = {
"lamball": ("fluffy_shield","Fluffy Shield","Пушистый щит","When activated, equips to the player and becomes a shield. Sometimes drops Wool on Ranch.","При активации становится щитом. Иногда даёт Шерсть на Ранчо."),
"cattiva": ("cat_helper","Cat Helper","Кошачья помощь","While in team, increases the player's max carrying capacity.","В команде увеличивает грузоподъёмность."),
"chikipi": ("egg_layer","Egg Layer","Несушка","Sometimes lays an Egg when assigned to Ranch.","Иногда откладывает Яйцо на Ранчо."),
"lifmunk": ("lifmunk_recoil","Lifmunk Recoil","Отдача Лифманка","Mounts the player's head and fires a submachine gun.","Садится на голову и стреляет."),
"foxparks": ("huggy_fire","Huggy Fire","Обнимательный огонь","Equips to the player and becomes a flamethrower.","Становится огнемётом."),
"anubis": ("guardian_of_the_desert","Guardian of the Desert","Страж пустыни","Applies Ground damage to the player's attacks. Can be ridden.","Земляной урон атакам игрока. Можно оседлать."),
"jetragon": ("aerial_missile","Aerial Missile","Воздушная ракета","Flying mount. Fires homing missiles.","Летающий маунт. Самонаводящиеся ракеты."),
"frostallion": ("ice_steed","Ice Steed","Ледяной скакун","Flying mount. Changes player attacks to Ice.","Летающий маунт. Атаки игрока — Лёд."),
"grizzbolt": ("yellow_tank","Yellow Tank","Жёлтый танк","Can be ridden. Enhances Electric attacks.","Можно оседлать. Усиливает электрические атаки."),
"lyleen": ("harvest_goddess","Harvest Goddess","Богиня урожая","Increases work of Grass pals; can plant.","Ускоряет травяных палов; посадка."),
"orserk": ("ferocious_thunder_dragon","Ferocious Thunder Dragon","Свирепый громовой дракон","Electric Pals deal more damage while in party.","Электрические палы наносят больше урона."),
"shadowbeak": ("modified_dna","Modified DNA","Модифицированная ДНК","Flying mount. Enhances Dark attacks.","Летающий маунт. Усиливает тёмные атаки."),
"vixy": ("dig_helper","Dig Helper","Помощник-копатель","Sometimes digs up items when assigned to Ranch.","Иногда выкапывает предметы на Ранчо."),
"pengullet": ("pengullet_cannon","Pengullet Cannon","Пушка Пенгуллета","Equips to player and becomes a rocket launcher (self-destructs).","Становится ракетницей (самоуничтожение)."),
"penking": ("brave_sailor","Brave Sailor","Отважный моряк","While fighting together, attack + against Water-weak foes / Water work boost.","Усиление в бою; водные работы."),
"mossanda": ("grenadier_panda","Grenadier Panda","Панда-гренадер","Can be ridden. Fires a grenade launcher.","Можно оседлать. Гранатомёт."),
"relaxaurus": ("hungry_missile","Hungry Missile","Голодная ракета","Can be ridden. Fires a missile launcher.","Можно оседлать. Ракетница."),
"blazamut": ("magma_kaiser","Magma Kaiser","Магма-кайзер","Can be ridden. Enhances Fire attacks.","Можно оседлать. Усиливает огонь."),
"suzaku": ("wings_of_flame","Wings of Flame","Крылья пламени","Flying mount. Enhances Fire attacks.","Летающий маунт. Усиливает огонь."),
"paladius": ("holy_knight_of_legend","Holy Knight of Legend","Святой рыцарь легенды","Can be ridden. Player gets increased defense.","Можно оседлать. Повышает защиту игрока."),
"necromus": ("dark_knight_of_legend","Dark Knight of Legend","Тёмный рыцарь легенды","Can be ridden. Player gets increased attack.","Можно оседлать. Повышает атаку игрока."),
"felbat": ("life_steal","Life Steal","Кража жизни","While fighting together, player recovers HP over time.","В бою игрок восстанавливает HP."),
"gobfin": ("angry_shark","Angry Shark","Злая акула","While in team, increases player attack.","В команде повышает атаку игрока."),
"direhowl": ("direhowl_rider","Direhowl Rider","Наездник Дайрхаула","Can be ridden. Enhances movement speed.","Можно оседлать. Скорость передвижения."),
"vanwyrm": ("aerial_marauder","Aerial Marauder","Воздушный мародёр","Flying mount. Increases player damage while mounted.","Летающий маунт. Больше урона."),
"kitsun": ("clear_mind","Clear Mind","Ясный разум","Can be ridden. Unaffected by cold/heat while mounted.","Маунт. Иммунитет к температуре."),
"chillet": ("wumpo_ride","Wumpo?","Ледяной скакун","Can be ridden. Applies Dragon to player attacks.","Маунт. Драконий урон атакам игрока."),
"univolt": ("swift_deity","Swift Deity","Стремительное божество","Can be ridden. Applies Electric to player attacks.","Маунт. Электрический урон атакам игрока."),
"rayhound": ("taser_unit","Taser Unit","Тазер","Can be ridden. Releases electric shocks.","Маунт. Электрические разряды."),
"nitemary": ("nightmare_bloom","Nightmare Bloom","Цветок кошмара","Support skill for Dark combat.","Поддержка в тёмном бою."),
"knocklem": ("heavy_metal_tank","Heavy Metal Tank","Тяжёлый металлический танк","Powerful base transporter and miner.","Мощный переносчик и шахтёр."),
"selyne": ("moonlight_grace","Moonlight Grace","Благодать лунного света","Support / combat partner skill.","Поддержка / боевой навык."),
"bastigor": ("ice_golem","Ice Golem","Ледяной голем","Tower-related ice specialist.","Ледяной специалист башни."),
}

work_overrides = {
"anubis": {"handiwork":4,"mining":3,"transporting":2},
"jetragon": {"gathering":3},
"lyleen": {"planting":4,"handiwork":3,"medicine":3,"gathering":2},
"orserk": {"generating_electricity":4,"handiwork":2,"transporting":3},
"grizzbolt": {"generating_electricity":3,"handiwork":2,"lumbering":2,"transporting":3},
"relaxaurus": {"watering":2,"transporting":3},
"jormuntide": {"watering":4},
"jormuntide_ignis": {"kindling":4},
"blazamut": {"kindling":3,"mining":4},
"frostallion": {"cooling":4},
"helzephyr": {"transporting":3},
"astegon": {"mining":4,"handiwork":1},
"wumpo": {"cooling":2,"handiwork":2,"lumbering":3,"transporting":4},
"wumpo_botan": {"planting":1,"handiwork":2,"lumbering":3,"transporting":4},
"mossanda": {"planting":2,"handiwork":2,"lumbering":2,"transporting":3},
"mossanda_lux": {"generating_electricity":2,"handiwork":2,"lumbering":2,"transporting":3},
"vixy": {"gathering":1,"farming":1},
"lamball": {"handiwork":1,"transporting":1,"farming":1},
"chikipi": {"gathering":1,"farming":1},
"lifmunk": {"planting":1,"handiwork":1,"lumbering":1,"medicine":1,"gathering":1},
"penking": {"watering":2,"handiwork":2,"mining":2,"cooling":2,"transporting":2},
"digtoise": {"mining":3},
"felbat": {"medicine":3},
"lovander": {"handiwork":2,"medicine":2,"transporting":2,"mining":1},
"lunaris": {"handiwork":3,"transporting":1,"gathering":1},
"katress": {"handiwork":2,"medicine":2,"transporting":2},
"verdash": {"planting":2,"handiwork":3,"lumbering":2,"transporting":2,"gathering":3},
"vaelet": {"planting":2,"handiwork":2,"medicine":3,"transporting":1,"gathering":2},
"sibelyx": {"medicine":2,"cooling":2,"farming":1},
"petallia": {"planting":3,"handiwork":2,"medicine":2,"transporting":1,"gathering":2},
"quivern": {"handiwork":1,"mining":2,"transporting":3,"gathering":2},
"beakon": {"generating_electricity":2,"handiwork":2,"transporting":3,"gathering":1},
"ragnahawk": {"kindling":3,"transporting":3},
"faleris": {"kindling":3,"transporting":3},
"mammorest": {"planting":2,"lumbering":2,"mining":2},
"reptyro": {"kindling":3,"mining":3},
"cryolinx": {"handiwork":1,"lumbering":2,"cooling":3},
"menasting": {"mining":3,"lumbering":2},
"warsect": {"planting":1,"handiwork":1,"lumbering":3,"transporting":3},
"elizabee": {"planting":2,"handiwork":2,"lumbering":1,"medicine":2,"gathering":2},
"kingpaca": {"gathering":1},
"sweepa": {"gathering":2,"cooling":2},
"univolt": {"generating_electricity":2,"lumbering":1},
"rayhound": {"generating_electricity":2,"lumbering":1},
"vanwyrm": {"kindling":1,"transporting":3},
"bushi": {"kindling":2,"handiwork":1,"lumbering":3,"transporting":2,"gathering":1},
"incineram": {"kindling":1,"handiwork":2,"mining":1,"transporting":2},
"nitemary": {"handiwork":2,"medicine":3,"transporting":1},
"knocklem": {"mining":4,"transporting":4},
"prixter": {"mining":2,"handiwork":1,"lumbering":2},
"sootseer": {"kindling":2,"handiwork":1,"mining":2,"farming":1},
"azurmane": {"generating_electricity":3,"lumbering":2,"gathering":2},
"bastigor": {"handiwork":1,"mining":3,"cooling":2,"transporting":2},
"gildane": {"mining":1,"gathering":2,"lumbering":1},
"lyleen_noct": {"handiwork":3,"medicine":3,"gathering":2},
"shadowbeak": {"gathering":1},
"paladius": {"lumbering":2,"mining":2},
"necromus": {"lumbering":2,"mining":2},
"suzaku": {"kindling":3},
"suzaku_aqua": {"watering":3},
}


def default_work(e1, e2, power):
    w = {}
    if e1 == "Fire" or e2 == "Fire":
        w["kindling"] = 2 if power < 600 else 1
    if e1 == "Water" or e2 == "Water":
        w["watering"] = 2 if power < 600 else 1
    if e1 == "Grass" or e2 == "Grass":
        w["planting"] = 2 if power < 600 else 1
    if e1 == "Electric" or e2 == "Electric":
        w["generating_electricity"] = 2 if power < 600 else 1
    if e1 == "Ice" or e2 == "Ice":
        w["cooling"] = 2 if power < 600 else 1
    if e1 == "Ground" or e2 == "Ground":
        w["mining"] = 2 if power < 600 else 1
    if power > 1000:
        w.setdefault("handiwork", 1)
        w.setdefault("gathering", 1)
    elif power > 500:
        w.setdefault("handiwork", 2)
        w.setdefault("transporting", 2)
    else:
        w.setdefault("handiwork", 3)
        w.setdefault("transporting", 3)
        w.setdefault("lumbering", 2)
    return w


def stats_for(rarity, power):
    base = {
        "common": (70, 70, 70, 100),
        "uncommon": (90, 90, 90, 150),
        "rare": (110, 110, 110, 250),
        "epic": (130, 130, 130, 400),
        "legendary": (140, 140, 140, 550),
    }
    hp, atk, deff, food = base[rarity]
    if power < 100:
        hp, atk = hp + 20, atk + 25
    return hp, atk, deff, food


special_combos = [
("blazehowl", "felbat", "blazehowl_noct"),
("broncherry", "fuack", "broncherry_aqua"),
("bushi", "sootseer", "bushi_noct"),
("caprity", "tarantriss", "caprity_noct"),
("chillet", "arsox", "chillet_ignis"),
("croajiro", "bushi_noct", "croajiro_noct"),
("cryolinx", "dazemu", "cryolinx_terra"),
("dazzi", "omascul", "dazzi_noct"),
("dinossom", "rayhound", "dinossom_lux"),
("dumud", "eikthyrdeer_terra", "dumud_gild"),
("eikthyrdeer", "hangyu", "eikthyrdeer_terra"),
("elphidran", "surfent", "elphidran_aqua"),
("faleris", "jormuntide", "faleris_aqua"),
("fenglope", "azurmane", "fenglope_lux"),
("foxparks", "foxcicle", "foxparks_cryst"),
("frostallion", "helzephyr", "frostallion_noct"),
("fuack", "flambelle", "fuack_ignis"),
("gobfin", "rooby", "gobfin_ignis"),
("gorirat", "kikit", "gorirat_terra"),
("hangyu", "swee", "hangyu_cryst"),
("helzephyr", "beakon", "helzephyr_lux"),
("incineram", "maraith", "incineram_noct"),
("jolthog", "pengullet", "jolthog_cryst"),
("jormuntide", "blazehowl", "jormuntide_ignis"),
("kingpaca", "reindrix", "kingpaca_cryst"),
("kitsun", "nyafia", "kitsun_noct"),
("leezpunk", "flambelle", "leezpunk_ignis"),
("loupmoon", "sweepa", "loupmoon_cryst"),
("lyleen", "menasting", "lyleen_noct"),
("mammorest", "wumpo", "mammorest_cryst"),
("mau", "pengullet", "mau_cryst"),
("menasting", "knocklem", "menasting_terra"),
("mossanda", "grizzbolt", "mossanda_lux"),
("pengullet", "sparkit", "pengullet_lux"),
("penking", "rayhound", "penking_lux"),
("pyrin", "katress", "pyrin_noct"),
("quivern", "lullu", "quivern_botan"),
("relaxaurus", "sparkit", "relaxaurus_lux"),
("reptyro", "foxcicle", "reptyro_cryst"),
("ribbuny", "bristla", "ribbuny_botan"),
("robinquill", "fuddler", "robinquill_terra"),
("surfent", "dumud", "surfent_terra"),
("suzaku", "jormuntide", "suzaku_aqua"),
("vanwyrm", "foxcicle", "vanwyrm_cryst"),
("warsect", "digtoise", "warsect_terra"),
("katress", "wixen", "katress_ignis"),
("mossanda", "petallia", "lyleen"),
("vanwyrm", "anubis", "faleris"),
("mossanda", "rayhound", "grizzbolt"),
("grizzbolt", "relaxaurus", "orserk"),
("kitsun", "astegon", "shadowbeak"),
("paladius", "lunaris", "selyne"),
("frostallion", "anubis", "bastigor"),
("gildane", "eikthyrdeer_terra", "celesdir"),
]

same_species_only = [
    "chikipi", "blazamut_ryu", "paladius", "necromus", "frostallion", "jetragon",
    "bellanoir_libero", "mimog", "xenovader", "xenogard", "xenolord",
]

passives = [
("legend", "Legend", "Легенда", "positive", "legendary", "Attack +20%, Defense +20%, Work Speed +15%", "Атака +20%, Защита +20%, Скорость работы +15%"),
("musclehead", "Musclehead", "Качок", "positive", "gold", "Attack +30%, Work Speed -50%", "Атака +30%, Скорость работы -50%"),
("ferocious", "Ferocious", "Свирепый", "positive", "gold", "Attack +20%", "Атака +20%"),
("burly_body", "Burly Body", "Крепыш", "positive", "gold", "Defense +20%", "Защита +20%"),
("serenity", "Serenity", "Спокойствие", "positive", "gold", "Active skill cooldown -30%, Attack +10%", "КД навыков -30%, Атака +10%"),
("vampiric", "Vampiric", "Вампиризм", "positive", "gold", "Absorbs a portion of damage dealt as HP", "Поглощает часть урона как HP"),
("demon_god", "Demon God", "Демон-бог", "positive", "gold", "Attack +30%, Defense +5%", "Атака +30%, Защита +5%"),
("diamond_body", "Diamond Body", "Алмазное тело", "positive", "gold", "Defense +30%", "Защита +30%"),
("divine_dragon", "Divine Dragon", "Божественный дракон", "positive", "gold", "Dragon attack +20%", "Драконий урон +20%"),
("eternal_flame", "Eternal Flame", "Вечное пламя", "positive", "gold", "Fire attack +20%", "Огненный урон +20%"),
("lord_of_lightning", "Lord of Lightning", "Повелитель молний", "positive", "gold", "Electric attack +20%", "Электрический урон +20%"),
("lord_of_the_underworld", "Lord of the Underworld", "Повелитель преисподней", "positive", "gold", "Dark attack +20%", "Тёмный урон +20%"),
("ice_emperor", "Ice Emperor", "Ледяной император", "positive", "gold", "Ice attack +20%", "Ледяной урон +20%"),
("earth_emperor", "Earth Emperor", "Земляной император", "positive", "gold", "Ground attack +20%", "Земляной урон +20%"),
("spirit_emperor", "Spirit Emperor", "Духовный император", "positive", "gold", "Grass attack +20%", "Травяной урон +20%"),
("lord_of_the_sea", "Lord of the Sea", "Повелитель морей", "positive", "gold", "Water attack +20%", "Водный урон +20%"),
("swift", "Swift", "Стремительный", "positive", "gold", "Movement speed +30%", "Скорость передвижения +30%"),
("runner", "Runner", "Бегун", "positive", "blue", "Movement speed +20%", "Скорость передвижения +20%"),
("nimble", "Nimble", "Проворный", "positive", "green", "Movement speed +10%", "Скорость передвижения +10%"),
("work_slave", "Work Slave", "Рабочий раб", "positive", "blue", "Work Speed +30%, Attack -30%", "Скорость работы +30%, Атака -30%"),
("artisan", "Artisan", "Ремесленник", "positive", "gold", "Work Speed +50%", "Скорость работы +50%"),
("serious", "Serious", "Серьёзный", "positive", "blue", "Work Speed +20%", "Скорость работы +20%"),
("lucky", "Lucky", "Удачливый", "positive", "gold", "Work Speed +15%, Attack +15%", "Скорость работы +15%, Атака +15%"),
("remarkable_craftsmanship", "Remarkable Craftsmanship", "Выдающееся мастерство", "positive", "gold", "Work Speed +75%", "Скорость работы +75%"),
("diet_lover", "Diet Lover", "Любитель диеты", "positive", "blue", "SAN / hunger decreases slower", "SAN/голод падают медленнее"),
("nocturnal", "Nocturnal", "Ночной", "positive", "blue", "Does not sleep at night", "Не спит ночью"),
("mine_foreman", "Mine Foreman", "Шахтёрский бригадир", "positive", "blue", "Player mining +25%", "Добыча игрока +25%"),
("logging_foreman", "Logging Foreman", "Бригадир лесорубов", "positive", "blue", "Player lumbering +25%", "Рубка игрока +25%"),
("brave", "Brave", "Храбрый", "positive", "green", "Attack +10%", "Атака +10%"),
("coward", "Coward", "Трус", "negative", "green", "Attack -10%", "Атака -10%"),
("clumsy", "Clumsy", "Неуклюжий", "negative", "green", "Work Speed -10%", "Скорость работы -10%"),
("slacker", "Slacker", "Бездельник", "negative", "blue", "Work Speed -30%", "Скорость работы -30%"),
("destructive", "Destructive", "Разрушительный", "negative", "blue", "SAN drops faster", "SAN падает быстрее"),
("bottomless_stomach", "Bottomless Stomach", "Бездонный желудок", "negative", "blue", "Hunger drops faster", "Голод растёт быстрее"),
("glutton", "Glutton", "Обжора", "negative", "green", "Hunger drops faster", "Голод растёт быстрее"),
("pacifist", "Pacifist", "Пацифист", "negative", "blue", "Attack -20%", "Атака -20%"),
("hooligan", "Hooligan", "Хулиган", "negative", "blue", "Work Speed -10%, Attack +15%", "Скорость работы -10%, Атака +15%"),
("unfit_for_work", "Unfit for Work", "Непригоден к работе", "negative", "blue", "Work Speed -40%", "Скорость работы -40%"),
("philanthropist", "Philanthropist", "Филантроп", "positive", "blue", "Breeding speed increased", "Ускоряет размножение"),
("infinite_stamina", "Infinite Stamina", "Бесконечная выносливость", "positive", "gold", "Max SAN higher", "Макс. SAN выше"),
("stronghold_strategist", "Stronghold Strategist", "Стратег крепости", "positive", "gold", "Player defense +10% in party", "Защита игрока +10% в отряде"),
("vanguard", "Vanguard", "Авангард", "positive", "gold", "Player attack +10% in party", "Атака игрока +10% в отряде"),
("motivational_leader", "Motivational Leader", "Вдохновляющий лидер", "positive", "blue", "Player work speed +25%", "Скорость работы игрока +25%"),
]

actives = [
("air_cannon", "Air Cannon", "Воздушная пушка", "Neutral", 25, 2, "Fires compressed air.", "Сжатый воздух."),
("power_shot", "Power Shot", "Мощный выстрел", "Neutral", 35, 4, "Explosive blast.", "Взрывной снаряд."),
("power_bomb", "Power Bomb", "Мощная бомба", "Neutral", 70, 15, "Massive energy ball.", "Огромный шар энергии."),
("pal_blast", "Pal Blast", "Пал-взрыв", "Neutral", 150, 55, "Devastating energy blast.", "Разрушительная энергия."),
("ignis_blast", "Ignis Blast", "Огненный заряд", "Fire", 30, 2, "Hurls a ball of fire.", "Огненный шар."),
("spirit_fire", "Spirit Fire", "Дух огня", "Fire", 45, 7, "Homing fireballs.", "Самонаводящиеся огненные шары."),
("flare_arrow", "Flare Arrow", "Огненная стрела", "Fire", 55, 10, "Three flaming arrows.", "Три огненные стрелы."),
("ignis_breath", "Ignis Breath", "Огненное дыхание", "Fire", 70, 15, "Wide fire breath.", "Огненное дыхание."),
("fire_ball", "Fire Ball", "Огненный шар", "Fire", 55, 10, "Giant fire ball.", "Гигантский огненный шар."),
("ignis_rage", "Ignis Rage", "Ярость огня", "Fire", 120, 40, "Massive explosion.", "Мощный взрыв."),
("aqua_gun", "Aqua Gun", "Водяная пушка", "Water", 40, 4, "Ball of water.", "Водяной шар."),
("hydro_jet", "Hydro Jet", "Гидроструя", "Water", 30, 2, "High-pressure water.", "Струя воды."),
("bubble_blast", "Bubble Blast", "Взрыв пузырей", "Water", 65, 13, "Numerous bubbles.", "Множество пузырей."),
("aqua_burst", "Aqua Burst", "Водяной взрыв", "Water", 100, 30, "Giant water ball.", "Гигантский водяной шар."),
("hydro_laser", "Hydro Laser", "Гидролазер", "Water", 150, 55, "Pressurized water laser.", "Водный лазер."),
("seed_machine_gun", "Seed Machine Gun", "Семяпулемёт", "Grass", 50, 9, "Volley of seeds.", "Очередь семян."),
("seed_mine", "Seed Mine", "Семямина", "Grass", 65, 13, "Exploding seed.", "Взрывающееся семя."),
("grass_tornado", "Grass Tornado", "Травяное торнадо", "Grass", 80, 18, "Tornado of leaves.", "Торнадо из листьев."),
("spine_vine", "Spine Vine", "Шипастая лоза", "Grass", 95, 25, "Thorny vines.", "Колючие лозы."),
("solar_blast", "Solar Blast", "Солнечный взрыв", "Grass", 150, 55, "Solar energy blast.", "Солнечный луч."),
("spark_blast", "Spark Blast", "Искровой взрыв", "Electric", 30, 2, "Ball of electricity.", "Шар электричества."),
("shockwave", "Shockwave", "Ударная волна", "Electric", 40, 4, "Electric discharge.", "Электрический разряд."),
("electric_ball", "Electric Ball", "Электрический шар", "Electric", 50, 9, "Forward electric ball.", "Электрический шар."),
("lightning_streak", "Lightning Streak", "Полоса молний", "Electric", 75, 16, "Moving lightning.", "Молния вперёд."),
("lightning_strike", "Lightning Strike", "Удар молнии", "Electric", 120, 40, "Powerful lightning.", "Мощная молния."),
("ice_missile", "Ice Missile", "Ледяная ракета", "Ice", 30, 3, "Ice lances.", "Ледяные копья."),
("icicle_cutter", "Icicle Cutter", "Сосулька-резак", "Ice", 55, 10, "Crescent ice blade.", "Ледяной клинок."),
("iceberg", "Iceberg", "Айсберг", "Ice", 70, 15, "Ice spear under enemy.", "Ледяное копьё."),
("blizzard_spike", "Blizzard Spike", "Шип метели", "Ice", 130, 45, "Giant ice boulder.", "Ледяная глыба."),
("sand_blast", "Sand Blast", "Песчаный взрыв", "Ground", 40, 4, "Sticky mud.", "Ком грязи."),
("stone_blast", "Stone Blast", "Каменный взрыв", "Ground", 55, 10, "Barrage of stones.", "Град камней."),
("stone_cannon", "Stone Cannon", "Каменная пушка", "Ground", 70, 15, "Hurls a boulder.", "Валун."),
("sand_tornado", "Sand Tornado", "Песчаное торнадо", "Ground", 80, 18, "Sand tornado.", "Песчаное торнадо."),
("rock_lance", "Rock Lance", "Каменное копьё", "Ground", 150, 55, "Rock spear under enemy.", "Каменное копьё."),
("poison_blast", "Poison Blast", "Ядовитый взрыв", "Dark", 30, 2, "Poison sludge.", "Ядовитая жижа."),
("dark_ball", "Dark Ball", "Тёмный шар", "Dark", 40, 4, "Ball of darkness.", "Шар тьмы."),
("shadow_burst", "Shadow Burst", "Теневой взрыв", "Dark", 55, 10, "Dark energy burst.", "Взрыв тьмы."),
("nightmare_ball", "Nightmare Ball", "Шар кошмара", "Dark", 100, 30, "Giant darkness ball.", "Гигантский шар тьмы."),
("dark_laser", "Dark Laser", "Тёмный лазер", "Dark", 150, 55, "Dark energy laser.", "Лазер тьмы."),
("dragon_cannon", "Dragon Cannon", "Драконья пушка", "Dragon", 30, 2, "Draconic energy ball.", "Драконий заряд."),
("dragon_burst", "Dragon Burst", "Драконий взрыв", "Dragon", 55, 10, "Draconic discharge.", "Драконий разряд."),
("draconic_breath", "Draconic Breath", "Драконье дыхание", "Dragon", 70, 15, "Draconic breath.", "Драконье дыхание."),
("dragon_meteor", "Dragon Meteor", "Драконий метеор", "Dragon", 150, 55, "Dragon-shaped meteors.", "Драконьи метеоры."),
]

items = [
("pal_sphere", "Pal Sphere", "Пал-сфера", "sphere", "Basic capture sphere.", "Базовая сфера захвата."),
("mega_sphere", "Mega Sphere", "Мега-сфера", "sphere", "Improved capture sphere.", "Улучшенная сфера."),
("giga_sphere", "Giga Sphere", "Гига-сфера", "sphere", "High-grade sphere.", "Высококачественная сфера."),
("hyper_sphere", "Hyper Sphere", "Гипер-сфера", "sphere", "Advanced sphere.", "Продвинутая сфера."),
("ultra_sphere", "Ultra Sphere", "Ультра-сфера", "sphere", "Very high capture power.", "Очень высокая сила захвата."),
("legendary_sphere", "Legendary Sphere", "Легендарная сфера", "sphere", "Top-tier sphere.", "Сфера высшего уровня."),
("wood", "Wood", "Дерево", "material", "Chop trees.", "Рубите деревья."),
("stone", "Stone", "Камень", "material", "Mine rocks.", "Добывайте камни."),
("fiber", "Fiber", "Волокно", "material", "From bushes and trees.", "Из кустов и деревьев."),
("ingot", "Ingot", "Слиток", "material", "Smelted from Ore.", "Выплавляется из Руды."),
("ore", "Ore", "Руда", "material", "Mined from ore nodes.", "Из жил руды."),
("coal", "Coal", "Уголь", "material", "Fuel and crafting.", "Топливо и крафт."),
("quartz", "Pure Quartz", "Чистый кварц", "material", "Cold regions.", "Холодные регионы."),
("crude_oil", "Crude Oil", "Сырая нефть", "material", "Late-game oil nodes.", "Нефть поздней игры."),
("pal_metal_ingot", "Pal Metal Ingot", "Пал-металл", "material", "Advanced metal.", "Продвинутый металл."),
("cake", "Cake", "Торт", "food", "Required for breeding.", "Нужен для разведения."),
("red_berries", "Red Berries", "Красные ягоды", "food", "Basic food.", "Базовая еда."),
("baked_berries", "Baked Berries", "Печёные ягоды", "food", "Cooked berries.", "Приготовленные ягоды."),
("wool", "Wool", "Шерсть", "material", "Lamball/Cremis ranch.", "Ранчо Лэмбол/Кремис."),
("egg", "Egg", "Яйцо", "food", "Chikipi ranch.", "Ранчо Чикипи."),
("milk", "Milk", "Молоко", "food", "Mozzarina ranch.", "Ранчо Моццарины."),
("honey", "Honey", "Мёд", "food", "Beegarde ranch.", "Ранчо Бигарда."),
("high_quality_cloth", "High Quality Cloth", "Ткань HQ", "material", "Crafted cloth.", "Крафт ткани."),
("ancient_civilization_parts", "Ancient Civilization Parts", "Части древней цивилизации", "material", "Bosses and chests.", "Боссы и сундуки."),
("assault_rifle", "Assault Rifle", "Штурмовая винтовка", "weapon", "Mid-late firearm.", "Огнестрел mid/late."),
("pump_action_shotgun", "Pump-Action Shotgun", "Помповый дробовик", "weapon", "Close-range power.", "Ближний бой."),
("rocket_launcher", "Rocket Launcher", "Ракетница", "weapon", "Explosive heavy weapon.", "Взрывное оружие."),
("metal_helm", "Metal Helm", "Металлический шлем", "armor", "Mid-game head armor.", "Шлем mid-game."),
("heat_resistant_pelt_armor", "Heat Resistant Pelt Armor", "Жаростойкая броня", "armor", "Heat protection.", "Защита от жары."),
("cold_resistant_pelt_armor", "Cold Resistant Pelt Armor", "Морозостойкая броня", "armor", "Cold protection.", "Защита от холода."),
]

bosses = [
(1, "zoe_grizzbolt", "Zoe & Grizzbolt", "Зоя и Гризболт", "Rayne Syndicate Tower", "Башня Синдиката Рейн", 10, "Electric", None,
 "Early tower. Bring Water pals (Pengullet, Fuack, Penking).", "Ранняя башня. Водные палы (Пенгуллет, Фуак, Пенкинг).", "penking,surfent,jormuntide"),
(2, "lily_lyleen", "Lily & Lyleen", "Лили и Лайлин", "Free Pal Alliance Tower", "Башня Альянса Свободных Палов", 25, "Grass", None,
 "Fire pals excel (Arsox, Vanwyrm, Ragnahawk).", "Огненные палы (Арсокс, Ванвирм, Рагнахок).", "ragnahawk,pyrin,blazehowl"),
(3, "axel_orserk", "Axel & Orserk", "Аксель и Орсерк", "Brothers of the Eternal Pyre Tower", "Башня Братьев Вечного Пламени", 35, "Electric", "Dragon",
 "Ground helps; beware Electric. Anubis recommended.", "Земля; осторожно с электричеством. Анубис.", "anubis,digtoise,warsect"),
(4, "marcus_faleris", "Marcus & Faleris", "Маркус и Фалерис", "PIDF Tower", "Башня PIDF", 45, "Fire", None,
 "Water and Ground recommended.", "Вода и Земля.", "jormuntide,surfent,anubis"),
(5, "victor_shadowbeak", "Victor & Shadowbeak", "Виктор и Шэдоубик", "PAL Genetic Research Unit Tower", "Башня Генетических исследований PAL", 50, "Dark", None,
 "Dragon/Neutral strong. High-level team required.", "Дракон/Нейтрал. Сильная команда.", "jetragon,paladius,astegon"),
]

guides = [
("early_game", "Early Game Guide", "Гайд по ранней игре", "progress",
 "Base basics: campfire, palbox, beds. Catch Lamball, Cattiva, Lifmunk, Foxparks, Pengullet. Unlock Ranch and Breeding Farm (lv 19).",
 "База: костёр, палбокс, кровати. Ловите Лэмбола, Кэттиву, Лифманка, Фокспаркса, Пенгуллета. Ранчо и Ферма разведения (ур. 19)."),
("base_pals", "Best Base Pals", "Лучшие палы для базы", "base",
 "Anubis (Handiwork 4), Lyleen (Planting 4), Orserk (Electricity 4), Jormuntide (Watering 4), Frostallion (Cooling 4), Knocklem/Astegon (Mining), Wumpo (Transport 4), Felbat (Medicine).",
 "Анубис (Ручная работа 4), Лайлин (Посадка 4), Орсерк (Электричество 4), Йормунтид (Полив 4), Фросталлион (Охлаждение 4), Ноклем/Астегон (Добыча), Вумпо (Перенос 4), Фелбат (Медицина)."),
("combat_teams", "Best Combat Teams", "Лучшие боевые команды", "combat",
 "Legendaries: Jetragon, Frostallion/Noct, Necromus, Paladius, Shadowbeak, Orserk. Meta passives: Legend, Musclehead, Ferocious, Demon God, Serenity, Vampiric.",
 "Легендарки: Джетрагон, Фросталлион/Нокт, Некромус, Паладиус, Шэдоубик, Орсерк. Пассивки: Legend, Musclehead, Ferocious, Demon God, Serenity, Vampiric."),
("breeding_efficiency", "Efficient Breeding", "Эффективное разведение", "breeding",
 "Cake every egg. Philanthropist + Nocturnal speed up breeding. Breed passives on easy pals then transfer. Special combos for tower pals.",
 "Торт на каждое яйцо. Philanthropist + Nocturnal. Сначала пассивки на простых. Спец-комбо башенных палов."),
("resource_farming", "Resource Farming", "Фарм ресурсов", "farming",
 "Ore: Digtoise, Anubis, Astegon. Wood: Bushi, Wumpo. Quartz: cold biomes. Oil: late-game. Ancient parts: towers and alphas.",
 "Руда: Дигтойз, Анубис, Астегон. Дерево: Буши, Вумпо. Кварц: холод. Нефть: late. Древние части: башни и альфы."),
("mid_game", "Mid Game Guide", "Гайд по середине игры", "progress",
 "Push towers in order. Metal tools, better spheres, flying mounts. Breed Anubis and base specialists. Dungeons for schematics.",
 "Башни по порядку. Металл, сферы, летающие маунты. Анубис и специалисты базы. Данжи за схемами."),
("late_game", "Late Game Guide", "Гайд по поздней игре", "progress",
 "Hunt legendaries, perfect 4-passive pals, raid Bellanoir, optimize oil/power, multi-bases with max work suitability.",
 "Легендарки, 4 пассивки, рейды Беллануар, нефть/энергия, несколько баз."),
]

egg_by_rarity = {"common": "common", "uncommon": "common", "rare": "large", "epic": "large", "legendary": "huge"}

BIOMES = {
    "Neutral": "Starting isle / plains",
    "Fire": "Volcanic / desert",
    "Water": "Beaches / rivers",
    "Grass": "Forests",
    "Electric": "Plains / thunder areas",
    "Ice": "Snowy mountains",
    "Ground": "Deserts / rocky",
    "Dark": "Night / dungeons",
    "Dragon": "High-level zones / volcano",
}


def main():
    dirs = [
        "app/src/main/java/com/paldexpro/data/local/entity",
        "app/src/main/java/com/paldexpro/data/local/dao",
        "app/src/main/java/com/paldexpro/data/local",
        "app/src/main/java/com/paldexpro/data/repository",
        "app/src/main/java/com/paldexpro/data/seed",
        "app/src/main/java/com/paldexpro/domain/model",
        "app/src/main/java/com/paldexpro/domain/breeding",
        "app/src/main/java/com/paldexpro/ui/theme",
        "app/src/main/java/com/paldexpro/ui/navigation",
        "app/src/main/java/com/paldexpro/ui/components",
        "app/src/main/java/com/paldexpro/ui/screens/home",
        "app/src/main/java/com/paldexpro/ui/screens/paldex",
        "app/src/main/java/com/paldexpro/ui/screens/breeding",
        "app/src/main/java/com/paldexpro/ui/screens/skills",
        "app/src/main/java/com/paldexpro/ui/screens/items",
        "app/src/main/java/com/paldexpro/ui/screens/bosses",
        "app/src/main/java/com/paldexpro/ui/screens/guides",
        "app/src/main/java/com/paldexpro/ui/screens/settings",
        "app/src/main/java/com/paldexpro/di",
        "app/src/main/res/values",
        "app/src/main/res/values-ru",
        "app/src/main/res/values-night",
        "app/src/main/res/xml",
        "app/src/main/res/drawable",
        "app/src/main/assets",
        "app/src/test/java/com/paldexpro",
        "gradle/wrapper",
    ]
    for d in dirs:
        (ROOT / d).mkdir(parents=True, exist_ok=True)

    seed = {
        "version": 1,
        "gameVersion": "1.0",
        "pals": [],
        "passives": [],
        "actives": [],
        "items": [],
        "bosses": [],
        "guides": [],
        "specialCombos": [],
        "sameSpeciesOnly": same_species_only,
    }

    for p in pals_raw:
        pid, dex, en, ru, e1, e2, power, eligible, idx, rarity = p
        hp, atk, deff, food = stats_for(rarity, power)
        work = work_overrides.get(pid) or default_work(e1, e2, power)
        ps = partner_skills.get(pid)
        seed["pals"].append({
            "id": pid,
            "dexNumber": dex,
            "nameEn": en,
            "nameRu": ru,
            "element1": e1,
            "element2": e2,
            "breedingPower": power,
            "eligibleChild": eligible,
            "indexNo": idx,
            "rarity": rarity,
            "hp": hp,
            "attack": atk,
            "defense": deff,
            "foodAmount": food,
            "eggSize": egg_by_rarity[rarity],
            "workSuitability": work,
            "partnerSkillId": ps[0] if ps else f"{pid}_skill",
            "partnerSkillNameEn": ps[1] if ps else f"{en} Partner Skill",
            "partnerSkillNameRu": ps[2] if ps else f"Навык партнёра {ru}",
            "partnerSkillDescEn": ps[3] if ps else f"Partner skill of {en}.",
            "partnerSkillDescRu": ps[4] if ps else f"Партнёрский навык {ru}.",
            "locationEn": BIOMES.get(e1, "Palpagos Islands"),
            "locationRu": BIOMES.get(e1, "Острова Палпагос"),
            "dropsEn": "Materials / Bones / Pal Fluids",
            "dropsRu": "Материалы / Кости / Пал-жидкости",
            "nightOnly": e1 == "Dark" and rarity in ("uncommon", "rare"),
        })

    for p in passives:
        seed["passives"].append({
            "id": p[0], "nameEn": p[1], "nameRu": p[2], "polarity": p[3],
            "tier": p[4], "descEn": p[5], "descRu": p[6],
        })
    for a in actives:
        seed["actives"].append({
            "id": a[0], "nameEn": a[1], "nameRu": a[2], "element": a[3],
            "power": a[4], "cooldown": a[5], "descEn": a[6], "descRu": a[7],
        })
    for i in items:
        seed["items"].append({
            "id": i[0], "nameEn": i[1], "nameRu": i[2], "category": i[3],
            "descEn": i[4], "descRu": i[5],
        })
    for b in bosses:
        seed["bosses"].append({
            "order": b[0], "id": b[1], "nameEn": b[2], "nameRu": b[3],
            "locationEn": b[4], "locationRu": b[5], "level": b[6],
            "element1": b[7], "element2": b[8], "strategyEn": b[9],
            "strategyRu": b[10], "counterPalIds": b[11],
        })
    for g in guides:
        seed["guides"].append({
            "id": g[0], "titleEn": g[1], "titleRu": g[2], "category": g[3],
            "bodyEn": g[4], "bodyRu": g[5],
        })
    for c in special_combos:
        seed["specialCombos"].append({"parentA": c[0], "parentB": c[1], "child": c[2]})

    out = ROOT / "app/src/main/assets/seed_data.json"
    out.write_text(json.dumps(seed, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")
    print(f"Pals={len(seed['pals'])} Passives={len(seed['passives'])} Actives={len(seed['actives'])} Special={len(seed['specialCombos'])}")


if __name__ == "__main__":
    main()
